#! /bin/sh
# $fiHeader: make-stub-file1,v 1.1 92/12/14 15:02:53 cer Exp $

header=$1
shift;
echo $header
echo "{"

for file in $*; do
	cat $file | sed -e 's/^/extern int /' -e 's/$/;/'
done

# I changed the assignment of the class variables to `i' to be
# arguments to a function.  The Sun's Solaris 2 C compiler was
# eliminating most of the assignments!  -dkl, 9/14/93

echo 'lisp_stub_dummy_caller('
for file in $*; do
	cat $file | sed -e 's/$/,/'
done
echo '0);'

echo "}"

echo 'lisp_stub_dummy_caller(i) {}'


