#! /bin/sh
# $Header: /repo/cvs.copy/clim2/misc/make-stub-file,v 1.5 1997/02/05 01:49:10 tomj Exp $

header=$1
shift;
echo $header
echo "{"
for file in $*; do
	cat $file | sed -e 's/$/();/'
done
echo "}"



