#! /bin/sh
# $fiHeader: make-stub-file,v 1.2 92/03/24 19:46:40 cer Exp $

header=$1
shift;
echo $header
echo "{ int i;"

for file in $*; do
	cat $file | sed -e 's/^/extern int /' -e 's/$/;/'
done

for file in $*; do
	cat $file | sed -e 's/^/i = /' -e 's/$/;/'
done

echo "}"



