#! /bin/sh
# $Header: /repo/cvs.copy/clim2/misc/make-stub-file,v 2.4 2003/12/15 18:35:14 layer Exp $

header=$1
shift;
echo $header
echo "{"
for file in $*; do
	cat $file | sed -e 's/$/();/'
done
echo "}"



