# $Header: /repo/cvs.copy/clim2/Makefile.unknown,v 1.2 1997/02/05 01:42:15 tomj Exp $
#
#  Makefile.unknown for CLIM 2.0
#

# Provide enough structure to do a "make clean"

include Makefile.defs

include Makefile.generic
