# $Header: /repo/cvs.copy/clim2/Makefile.dec3100,v 1.8.22.1 1998/05/19 01:04:14 layer Exp $
#
#  Makefile.dec3100 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.dec3100

TKLIB=/usr/lib/DXM/lib/Xm/libXm.a
XTLIB=/usr/lib/DXM/lib/Xt/libXt.a
XLIB=/usr/lib/libX11.a

XINCLUDES=-I/usr/lib/DXM/lib -I/usr/lib/DXM/lib/Xt

include Makefile.generic
