#
#  Makefile.macarm for CLIM 2.0
#

include Makefile.macos_common

CFLAGS = -m64 -arch arm64 -DAcl64Bit -dynamiclib -flat_namespace -single_module -DMACM1 -Wl,-no_adhoc_codesign -Wl,-macosx_version_min,12.0 -Wno-implicit-function-declaration

MAKE_SHARED = cc -arch arm64 -bundle -force_cpusubtype_ALL -flat_namespace -Wl,-macosx_version_min,12.0
