# $fiHeader: Makefile.rs6000,v 1.2 1994/12/18 06:44:40 duane Exp $
#
#  Makefile.rs6000 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.rs6000

CFLAGS	= -O -D_BSD -D_NO_PROTO -D_NONSTD_TYPES -D_MBI=void

TKLIB=-lXm
XTLIB=-lXt
XLIB=-lX11

XINCLUDES= -I/usr/include

PRODUCT-TK-OBJS= $(STATIC-XM-OBJS) $(SHARED-XM-OBJS)
MAKE_SHARED = make_shared

CL= /usr/fi/climdcl-devel

# This should be defined in make-dist. For CLIM devel (ie making
# slim images) we use climdcl-devel and don't use the shared library
# IMPORTS = ../src/ucl.exp

stubs = c2stubs

SAVEEXP = /bin/mv ucl.exp ucl.exp.climsave
RESTEXP = /bin/mv ucl.exp.climsave ucl.exp

include Makefile.generic
