# $fiHeader: Makefile,v 1.74 93/02/10 10:04:04 cer Exp $
#
#  Makefile.sun4 for CLIM 2.0
#

include Makefile.defs

MOTIFLIB=/x11/R4/sun4-lib/libXm$(DEBUGLIB).a
MOTIFLIB_d=/x11/R4/sun4-lib/libXm_d.a
XLIB= /x11/R4/sun4-lib/libX11$(DEBUGLIB).a 
XTLIB=/x11/R4/sun4-lib/libXt$(DEBUGLIB).a
XINCLUDES=-I/x11/motif-1.1/lib

include Makefile.generic
