# $fiHeader: Makefile.sgi4d-svr4,v 1.5 1995/05/15 07:17:42 duane Exp $
#
#  Makefile.sigi4d-svr4 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.sgi4d-svr4

TKLIB=-lXm
XTLIB=-lXt
XLIB=-lX11

XINCLUDES=-I/usr/include

PRODUCT-TK-OBJS= $(STATIC-XM-OBJS) $(SHARED-XM-OBJS)

PICFLAGS = -KPIC
SHAREFLAGS = -shared -all
MAKE_SHARED = ld

SAVEEXP = echo no exports file in this port
RESTEXP = echo no exports file in this port

include Makefile.generic
