# $Header: /repo/cvs.copy/clim2/Makefile.alpha,v 1.6.12.1 1998/05/18 23:56:10 layer Exp $
#
#  Makefile.alpha for CLIM 2.0

include Makefile.defs

Makefile=Makefile.alpha

CFLAGS = -O -G 0 -taso -xtaso -xtaso_short -resumption_safe
STD_DEFINES = -DDEC -DR5_XLIB -DSMT
AR = ar cqls

TKLIB=-lXm
XTLIB=-lXt
XLIB=-lX11

XINCLUDES=-I/usr/include

PRODUCT-OBJS= $(PRODUCT-GENERIC-OBJS) $(STATIC-XM-OBJS) $(SHARED-XM-OBJS)

PICFLAGS =
SHAREFLAGS =
MAKE_SHARED = make_shared

include Makefile.generic
