# $Header: /repo/cvs.copy/clim2/Makefile.unknown,v 2.4 2003/12/15 18:35:11 layer Exp $
#
#  Makefile.unknown for CLIM 2.0
#

# Provide enough structure to do a "make clean"

include Makefile.defs

include Makefile.generic
