# $Header: /repo/cvs.copy/clim2/Makefile.sun4,v 1.16 1997/02/05 01:42:04 tomj Exp $
#
#  Makefile.sun4 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.sun4

MOTIFHOME=/net/vapor/3rd/motif-1.2.4

XINCLUDES=-I$(MOTIFHOME)/usr/include

TKLIB=$(MOTIFHOME)/usr/lib/libXm.a
XTLIB=/net/louie/malle/colin/X11R5/Ximp-libs/libXt.a
XLIB=/net/louie/malle/colin/X11R5/Ximp-libs/libX11.a

AR = ar cq


include Makefile.generic
