#
#  Makefile.rs6000 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.rs6000

## For info on Motif1.2 vs Motif 2.1, see /usr/lpp/X11/README

CFLAGS	= -O -D_BSD -I/usr/include/Motif2.1

SET_LIBRARY_PATH= \
  LIBPATH=/usr/lpp/X11/lib/R6:/lib:/usr/lib; export LIBPATH; env

TKLIB=-L/usr/lpp/X11/lib/R6 -lXm

XTLIB=-lXt
XLIB=-lX11

XINCLUDES= -I/usr/include/Motif2.1

PRODUCT-OBJS= $(PRODUCT-GENERIC-OBJS) $(STATIC-XM-OBJS) $(SHARED-XM-OBJS)
MAKE_SHARED = sh ../src/bin/make_shared.ibm -make_exp ../src/bin/make_exp
STD_DEFINES =
AR = ar clq

# This should be defined in make-dist. For CLIM devel (ie making
# slim images) we use climdcl-devel and don't use the shared library
IMPORTS = stub-x.o stub-xt.o stub-motif.o ../src/lisp.exp

stubs = c2stubs

include Makefile.generic
