# $fiHeader: Makefile.hp700,v 1.2 93/05/13 16:22:43 cer Exp $
#
#  Makefile.rs6000 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.rs6000

CL=/usr/fi/dcl-devel

CFLAGS	= -O -D_BSD -D_NO_PROTO -D_NONSTD_TYPES -D_MBI=void

# 

MOTIFLIB=-lXm
MOTIFLIB_d=-lXm
XTLIB=-lXt
XLIB=-lX11
XINCLUDES= -I/usr/include -I/usr/include/Xm
XMINCLUDES=$(XINCLUDES)

# Make motif only. This is like the dec.
# Perhaps this should be included.

CLIM_FASLS_TO_MAKE = makeclimxmfasls
CLIMOBJS=$(GENERIC_PUBLIC_OBJS) $(XM_PUBLIC_OBJS) $(XM_LICENSED_OBJS)
CLIMFASLS= $(CLIM_XM_FASLS) $(CLIM_GENERIC_FASLS)
INSTALLED_CLIMOBJS=$(GENERIC_PUBLIC_OBJS) $(XM_PUBLIC_OBJS) $(XM_LICENSED_OBJS)

# To keep make from complaining about syntax:
MAIN_OBJ = mainxm.o

stubs = c2stubs

include Makefile.generic
