# $fiHeader: Makefile.sgi4d-svr4,v 1.8 1996/03/13 09:55:15 colin Exp $
#
#  Makefile.sigi4d-svr4 for CLIM 2.0
#

include Makefile.defs

Makefile=Makefile.sgi4d-svr4

TKLIB=-lXm
XTLIB=-lXt
XLIB=-lX11

XINCLUDES=-I/usr/include

PRODUCT-OBJS= $(PRODUCT-GENERIC-OBJS) $(STATIC-XM-OBJS) $(SHARED-XM-OBJS)

PICFLAGS = -KPIC
SHAREFLAGS = -shared -all
MAKE_SHARED = ld
STD_DEFINES = -DSVR4
AR = /usr/bin/ar cq

include Makefile.generic
