;; See the file LICENSE for the full license governing this code.
;;
;; $Id: xm-classes.lisp,v 2.7 2007/04/17 21:45:53 layer Exp $

(in-package :tk)

;;; This has to kept consistent with the Makefile

(defparameter *motif-classes* '("applicationShellWidgetClass"
				"compositeWidgetClass"
				"constraintWidgetClass"
				"coreWidgetClass"
				"objectClass"
				"overrideShellWidgetClass"
				"shellWidgetClass"
				"topLevelShellWidgetClass"
				"transientShellWidgetClass"
				"vendorShellWidgetClass"
				"wmShellWidgetClass"

				"xmArrowButtonGadgetClass"
				"xmArrowButtonWidgetClass"
				"xmBulletinBoardWidgetClass"
				"xmCascadeButtonGadgetClass"
				"xmCascadeButtonWidgetClass"
				"xmCommandWidgetClass"
				"xmDialogShellWidgetClass"
				"xmDrawingAreaWidgetClass"
				"xmDrawnButtonWidgetClass"
				"xmFileSelectionBoxWidgetClass"
				"xmFormWidgetClass"
				"xmFrameWidgetClass"
				"xmGadgetClass"
				"xmLabelGadgetClass"
				"xmLabelWidgetClass"
				"xmListWidgetClass"
				"xmMainWindowWidgetClass"
				"xmManagerWidgetClass"
				"xmMenuShellWidgetClass"
				"xmMessageBoxWidgetClass"
				"xmPanedWindowWidgetClass"
				"xmPrimitiveWidgetClass"
				"xmPushButtonGadgetClass"
				"xmPushButtonWidgetClass"
				"xmRowColumnWidgetClass"
				"xmScaleWidgetClass"
				"xmScrollBarWidgetClass"
				"xmScrolledWindowWidgetClass"
				"xmSelectionBoxWidgetClass"
				"xmSeparatorGadgetClass"
				"xmSeparatorWidgetClass"
				"xmTextFieldWidgetClass"
				"xmTextWidgetClass"
				"xmToggleButtonGadgetClass"
				"xmToggleButtonWidgetClass"
				"xmMyDrawingAreaWidgetClass"
				))
