;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Package: CL-USER; Base: 10; Lowercase: Yes -*-
;; copyright (c) 1985,1986 Franz Inc, Alameda, Ca.
;; copyright (c) 1986-1998 Franz Inc, Berkeley, CA  - All rights reserved.
;;
;; The software, data and information contained herein are proprietary
;; to, and comprise valuable trade secrets of, Franz, Inc.  They are
;; given in confidence by Franz, Inc. pursuant to a written license
;; agreement, and may be stored and used only in accordance with the terms
;; of such license.
;;
;; Restricted Rights Legend
;; ------------------------
;; Use, duplication, and disclosure of the software, data and information
;; contained herein by any agency, department or entity of the U.S.
;; Government are subject to restrictions of Restricted Rights for
;; Commercial Software developed at private expense as specified in
;; DOD FAR Supplement 52.227-7013 (c) (1) (ii), as applicable.
;;
;; $Id: packages.lisp,v 1.106.2.15 2001/12/12 01:01:07 layer Exp $

(in-package :common-lisp-user)

;;;"Copyright (c) 1991, 1992 Symbolics, Inc.  All rights reserved."


;; Define the CLIM-LISP package, a package designed to mimic ANSI Common Lisp
;; as closely as possible (including CLOS).
(defpackage clim-lisp
  #+allegro (:implementation-packages :clim-lisp :clim-utils)
  ;; 28Jan97 added allegro package for aclpc since mop stuff was moved
  ;; there in 3.0.1 -tjm
 (:use common-lisp #+allegro clos #+allegro stream #+aclpc allegro)

 ;; Import these symbols so that we can define methods for them.
 (:shadow pathname truename)

 ;; Shadow this everywhere to make it a generic function
 (:shadow interactive-stream-p)

 #+allegro
 (:import-from :excl #:non-dynamic-extent)

 (:export
   &allow-other-keys
   &aux
   &body
   &environment
   &key
   &optional
   &rest
   &whole
   *
   **
   ***
   *break-on-signals*
   *compile-file-pathname*
   *compile-file-truename*
   *compile-print*
   *compile-verbose*
   *debug-io*
   *debugger-hook*
   *default-pathname-defaults*
   *error-output*
   *features*
   *gensym-counter*
   *load-pathname*
   *load-print*
   *load-truename*
   *load-verbose*
   *macroexpand-hook*
   *package*
   *print-array*
   *print-base*
   *print-case*
   *print-circle*
   *print-escape*
   *print-gensym*
   *print-length*
   *print-level*
   *print-lines*
   *print-miser-width*
   *print-pprint-dispatch*
   *print-pretty*
   *print-radix*
   *print-readably*
   *print-right-margin*
   *query-io*
   *random-state*
   *read-base*
   *read-default-float-format*
   *read-eval*
   *read-suppress*
   *readtable*
   *standard-input*
   *standard-output*
   *terminal-io*
   *trace-output*
   +
   ++
   +++
   -
   /
   //
   ///
   /=
   1+
   1-
   <
   <=
   =
   >
   >=
   abort
   abs
   acons
   acos
   acosh
   add-method
   adjoin
   adjust-array
   adjustable-array-p
   allocate-instance
   alpha-char-p
   alphanumericp
   and
   append
   apply
   apropos
   apropos-list
   aref
   arithmetic-error
   arithmetic-error-operands
   arithmetic-error-operation
   array
   array-dimension
   array-dimension-limit
   array-dimensions
   array-displacement
   array-element-type
   array-has-fill-pointer-p
   array-in-bounds-p
   array-rank
   array-rank-limit
   array-row-major-index
   array-total-size
   array-total-size-limit
   arrayp
   ash
   asin
   asinh
   assert
   assoc
   assoc-if
   assoc-if-not
   atan
   atanh
   atom
   base-char
   base-string
   bignum
   bit
   bit-and
   bit-andc1
   bit-andc2
   bit-eqv
   bit-ior
   bit-nand
   bit-nor
   bit-not
   bit-orc1
   bit-orc2
   bit-vector
   bit-vector-p
   bit-xor
   block
   boole
   boole-1
   boole-2
   boole-and
   boole-andc1
   boole-andc2
   boole-c1
   boole-c2
   boole-clr
   boole-eqv
   boole-ior
   boole-nand
   boole-nor
   boole-orc1
   boole-orc2
   boole-set
   boole-xor
   #-aclpc boolean
   both-case-p
   boundp
   break
   broadcast-stream
   broadcast-stream-streams
   built-in-class
   butlast
   byte
   byte-position
   byte-size
   caaaar
   caaadr
   caaar
   caadar
   caaddr
   caadr
   caar
   cadaar
   cadadr
   cadar
   caddar
   cadddr
   caddr
   cadr
   call-arguments-limit
   call-method
   call-next-method
   car
   case
   catch
   ccase
   cdaaar
   cdaadr
   cdaar
   cdadar
   cdaddr
   cdadr
   cdar
   cddaar
   cddadr
   cddar
   cdddar
   cddddr
   cdddr
   cddr
   cdr
   ceiling
   cell-error
   cell-error-name
   cerror
   change-class
   char
   char-code
   char-code-limit
   char-downcase
   char-equal
   char-greaterp
   char-int
   char-lessp
   char-name
   char-not-equal
   char-not-greaterp
   char-not-lessp
   char-upcase
   char/=
   char<
   char<=
   char=
   char>
   char>=
   character
   characterp
   check-type
   cis
   class
   class-direct-subclasses
   class-direct-superclasses
   class-name
   class-of
   class-precedence-list
   class-prototype
   clear-input
   clear-output
   close
   clrhash
   code-char
   coerce
   compilation-speed
   compile
   compile-file
   compile-file-environment-p
   compile-file-pathname
   compiled-function
   compiled-function-p
   compiler-macro
   compiler-macro-function
   complement
   complex
   complexp
   compute-applicable-methods
   compute-restarts
   concatenate
   concatenated-stream
   concatenated-stream-streams
   cond
   condition
   conjugate
   cons
   consp
   constantly
   constantp
   continue
   control-error
   copy-alist
   copy-list
   copy-pprint-dispatch
   copy-readtable
   copy-seq
   copy-structure
   copy-symbol
   copy-tree
   cos
   cosh
   count
   count-if
   count-if-not
   ctypecase
   debug
   decf
   declaim
   declaration
   declare
   decode-float
   decode-universal-time
   defclass
   defconstant
   defgeneric
   define-compiler-macro
   define-condition
   define-method-combination
   define-modify-macro
   define-setf-expander
   defmacro
   defmethod
   defpackage
   defparameter
   defsetf
   defstruct
   deftype
   defun
   defvar
   delete
   delete-duplicates
   delete-file
   delete-if
   delete-if-not
   delete-package
   denominator
   deposit-field
   describe
   describe-object
   destructuring-bind
   digit-char
   digit-char-p
   directory
   directory-namestring
   disassemble
   division-by-zero
   do
   do*
   do-all-symbols
   do-external-symbols
   do-symbols
   documentation
   dolist
   dotimes
   double-float
   double-float-epsilon
   double-float-negative-epsilon
   dpb
   dribble
   dynamic-extent
   ecase
   echo-stream
   echo-stream-input-stream
   echo-stream-output-stream
   ed
   eighth
   elt
   encode-universal-time
   end-of-file
   endp
   enough-namestring
   ensure-generic-function
   eq
   eql
   equal
   equalp
   error
   etypecase
   eval
   eval-when
   evenp
   every
   exp
   export
   expt
   extended-char
   fboundp
   fceiling
   fdefinition
   ffloor
   fifth
   file-author
   file-error
   file-error-pathname
   file-length
   file-namestring
   file-position
   file-stream
   file-string-length
   file-write-date
   fill
   fill-pointer
   find
   find-all-symbols
   find-class
   find-if
   find-if-not
   find-method
   find-package
   find-restart
   find-symbol
   finish-output
   first
   fixnum
   flet
   float
   float-digits
   float-precision
   float-radix
   float-sign
   floating-point-inexact
   floating-point-invalid-operation
   floating-point-overflow
   floating-point-underflow
   floatp
   floor
   fmakunbound
   force-output
   format
   formatter
   fourth
   fresh-line
   fround
   ftruncate
   ftype
   funcall
   funcallable-standard-class
   function
   function-keywords
   function-lambda-expression
   functionp
   gcd
   generic-flet
   generic-function
   generic-labels
   gensym
   gentemp
   get
   get-decoded-time
   get-dispatch-macro-character
   get-internal-real-time
   get-internal-run-time
   get-macro-character
   get-output-stream-string
   get-properties
   get-setf-expansion
   get-universal-time
   getf
   gethash
   go
   graphic-char-p
   handler-bind
   handler-case
   hash-table
   hash-table-count
   hash-table-p
   hash-table-rehash-size
   hash-table-rehash-threshold
   hash-table-size
   hash-table-test
   host-namestring
   identity
   if
   ignorable
   ignore
   ignore-errors
   imagpart
   import
   in-package
   incf
   initialize-instance
   inline
   input-stream-p
   inspect
   integer
   integer-decode-float
   integer-length
   integerp
   interactive-stream-p
   intern
   internal-time-units-per-second
   intersection
   invalid-method-error
   invoke-debugger
   invoke-restart
   invoke-restart-interactively
   isqrt
   keyword
   keywordp
   labels
   lambda
   lambda-list-keywords
   lambda-parameters-limit
   last
   lcm
   ldb
   ldb-test
   ldiff
   least-negative-double-float
   least-negative-long-float
   least-negative-normalized-double-float
   least-negative-normalized-long-float
   least-negative-normalized-short-float
   least-negative-normalized-single-float
   least-negative-short-float
   least-negative-single-float
   least-positive-double-float
   least-positive-long-float
   least-positive-normalized-double-float
   least-positive-normalized-long-float
   least-positive-normalized-short-float
   least-positive-normalized-single-float
   least-positive-short-float
   least-positive-single-float
   length
   let
   let*
   lisp-implementation-type
   lisp-implementation-version
   list
   list*
   list-all-packages
   list-length
   listen
   listp
   load
   load-logical-pathname-translations
   load-time-value
   locally
   log
   logand
   logandc1
   logandc2
   logbitp
   logcount
   logeqv
   logical-pathname
   logical-pathname-translations
   logior
   lognand
   lognor
   lognot
   logorc1
   logorc2
   logtest
   logxor
   long-float
   long-float-epsilon
   long-float-negative-epsilon
   long-site-name
   loop
   loop-finish
   lower-case-p
   machine-instance
   machine-type
   machine-version
   macro-function
   macroexpand
   macroexpand-1
   macrolet
   make-array
   make-broadcast-stream
   make-concatenated-stream
   make-condition
   make-dispatch-macro-character
   make-echo-stream
   make-hash-table
   make-instance
   make-instances-obsolete
   make-list
   make-load-form
   make-load-form-saving-slots
   make-method
   make-package
   make-pathname
   make-random-state
   make-sequence
   make-string
   make-string-input-stream
   make-string-output-stream
   make-symbol
   make-synonym-stream
   make-two-way-stream
   makunbound
   map
   map-into
   mapc
   mapcan
   mapcar
   mapcon
   maphash
   mapl
   maplist
   mask-field
   max
   member
   member-if
   member-if-not
   merge
   merge-pathnames
   method
   method-combination
   method-combination-error
   method-qualifiers
   min
   minusp
   mismatch
   mod
   most-negative-double-float
   most-negative-fixnum
   most-negative-long-float
   most-negative-short-float
   most-negative-single-float
   most-positive-double-float
   most-positive-fixnum
   most-positive-long-float
   most-positive-short-float
   most-positive-single-float
   muffle-warning
   multiple-value-bind
   multiple-value-call
   multiple-value-list
   multiple-value-prog1
   multiple-value-setq
   multiple-values-limit
   name-char
   namestring
   nbutlast
   nconc
   next-method-p
   nil
   nintersection
   ninth
   no-applicable-method
   no-next-method
   not
   notany
   notevery
   notinline
   nreconc
   nreverse
   nset-difference
   nset-exclusive-or
   nstring-capitalize
   nstring-downcase
   nstring-upcase
   nsublis
   nsubst
   nsubst-if
   nsubst-if-not
   nsubstitute
   nsubstitute-if
   nsubstitute-if-not
   nth
   nth-value
   nthcdr
   null
   number
   numberp
   numerator
   nunion
   oddp
   open
   open-stream-p
   optimize
   or
   otherwise
   output-stream-p
   package
   package-error
   package-error-package
   package-name
   package-nicknames
   package-shadowing-symbols
   package-use-list
   package-used-by-list
   packagep
   pairlis
   parse-error
   parse-integer
   parse-namestring
   pathname
   pathname-device
   pathname-directory
   pathname-host
   pathname-match-p
   pathname-name
   pathname-type
   pathname-version
   pathnamep
   peek-char
   phase
   pi
   plusp
   pop
   position
   position-if
   position-if-not
   pprint
   pprint-dispatch
   pprint-exit-if-list-exhausted
   pprint-fill
   pprint-indent
   pprint-linear
   pprint-logical-block
   pprint-newline
   pprint-pop
   pprint-tab
   pprint-tabular
   prin1
   prin1-to-string
   princ
   princ-to-string
   print
   print-not-readable
   print-not-readable-object
   print-object
   print-unreadable-object
   probe-file
   proclaim
   prog
   prog*
   prog1
   prog2
   progn
   program-error
   progv
   provide
   psetf
   psetq
   push
   pushnew
   quote
   random
   random-state
   random-state-p
   rassoc
   rassoc-if
   rassoc-if-not
   ratio
   rational
   rationalize
   rationalp
   read
   read-byte
   read-char
   read-char-no-hang
   read-delimited-list
   read-from-string
   read-line
   read-preserving-whitespace
   reader-error
   readtable
   readtable-case
   readtablep
   real
   realp
   realpart
   reduce
   reinitialize-instance
   rem
   remf
   remhash
   remove
   remove-duplicates
   remove-if
   remove-if-not
   remove-method
   remprop
   rename-file
   rename-package
   replace
   require
   rest
   restart
   restart-bind
   restart-case
   restart-name
   return
   return-from
   revappend
   reverse
   room
   rotatef
   round
   row-major-aref
   rplaca
   rplacd
   safety
   satisfies
   sbit
   scale-float
   schar
   search
   second
   sequence
   serious-condition
   set
   set-difference
   set-dispatch-macro-character
   set-exclusive-or
   set-macro-character
   set-pprint-dispatch
   set-syntax-from-char
   setf
   setq
   seventh
   shadow
   shadowing-import
   shared-initialize
   shiftf
   short-float
   short-float-epsilon
   short-float-negative-epsilon
   short-site-name
   signal
   signed-byte
   signum
   simple-array
   simple-base-string
   simple-bit-vector
   simple-bit-vector-p
   simple-condition
   simple-condition-format-arguments
   simple-condition-format-control
   simple-error
   simple-string
   simple-string-p
   simple-type-error
   simple-vector
   simple-vector-p
   simple-warning
   sin
   single-float
   single-float-epsilon
   single-float-negative-epsilon
   sinh
   sixth
   sleep
   slot-boundp
   slot-exists-p
   slot-makunbound
   slot-missing
   slot-unbound
   slot-value
   software-type
   software-version
   some
   sort
   space
   special
   special-operator-p
   speed
   sqrt
   stable-sort
   standard-char
   standard-char-p
   standard-class
   standard-generic-function
   standard-method
   standard-object
   step
   storage-condition
   store-value
   stream
   stream-element-type
   stream-error
   stream-error-stream
   stream-external-format
   streamp
   string
   string-capitalize
   string-downcase
   string-equal
   string-greaterp
   string-left-trim
   string-lessp
   string-not-equal
   string-not-greaterp
   string-not-lessp
   string-right-trim
   string-stream
   string-trim
   string-upcase
   string/=
   string<
   string<=
   string=
   string>
   string>=
   stringp
   structure
   structure-class
   structure-object
   style-warning
   sublis
   subseq
   subsetp
   subst
   subst-if
   subst-if-not
   substitute
   substitute-if
   substitute-if-not
   subtypep
   svref
   sxhash
   symbol
   symbol-function
   symbol-macrolet
   symbol-name
   symbol-package
   symbol-plist
   symbol-value
   symbolp
   synonym-stream
   synonym-stream-symbol
   t
   tagbody
   tailp
   tan
   tanh
   tenth
   terpri
   the
   third
   throw
   time
   trace
   translate-logical-pathname
   translate-pathname
   tree-equal
   truename
   truncate
   two-way-stream
   two-way-stream-input-stream
   two-way-stream-output-stream
   type
   type-error
   type-error-datum
   type-error-expected-type
   type-of
   typecase
   typep
   unbound-slot
   unbound-slot-instance
   unbound-variable
   undefined-function
   unexport
   unintern
   union
   unless
   unread-char
   unsigned-byte
   untrace
   unuse-package
   unwind-protect
   update-instance-for-different-class
   update-instance-for-redefined-class
   upgraded-array-element-type
   upgraded-complex-part-type
   upper-case-p
   use-package
   use-value
   user-homedir-pathname
   values
   values-list
   variable
   vector
   vector-pop
   vector-push
   vector-push-extend
   vectorp
   warn
   warning
   when
   wild-pathname-p
   with-accessors
   with-compilation-unit
   with-condition-restarts
   with-hash-table-iterator
   with-input-from-string
   with-open-file
   with-open-stream
   with-output-to-string
   with-package-iterator
   with-simple-restart
   with-slots
   with-standard-io-syntax
   write
   write-byte
   write-char
   write-line
   write-string
   write-to-string
   y-or-n-p
   yes-or-no-p
   zerop)

 ;; Stream Proposal -- Classes and class predicates.
 #-clim-uses-lisp-stream-classes
 (:shadow
   fundamental-binary-input-stream
   fundamental-binary-output-stream
   fundamental-binary-stream
   fundamental-character-input-stream
   fundamental-character-output-stream
   fundamental-character-stream
   fundamental-input-stream
   fundamental-output-stream
   fundamental-stream
   input-stream-p
   open-stream-p
   output-stream-p
   streamp)

 #-(or clim-uses-lisp-stream-functions Lucid)
 (:shadow
   clear-input
   clear-output
   close
   finish-output
   force-output
   format
   fresh-line
   listen
   pathname
   peek-char
   read-byte
   read-char
   read-char-no-hang
   read-line
   stream-element-type
   terpri
   truename
   unread-char
   with-open-stream
   write-byte
   write-char
   write-string)

 ;; Export symbols from Gray stream proposal, sigh
 (:export
   fundamental-binary-input-stream
   fundamental-binary-output-stream
   fundamental-binary-stream
   fundamental-character-input-stream
   fundamental-character-output-stream
   fundamental-character-stream
   fundamental-input-stream
   fundamental-output-stream
   fundamental-stream
   stream-advance-to-column
   stream-clear-input
   stream-clear-output
   stream-finish-output
   stream-force-output
   stream-fresh-line
   stream-line-column
   stream-listen
   stream-peek-char
   stream-read-byte
   stream-read-char
   stream-read-char-no-hang
   stream-read-line
   stream-start-line-p
   stream-terpri
   stream-unread-char
   stream-write-byte
   stream-write-char
   stream-write-string)
)


;; Define the CLIM-SYS package
(defpackage clim-sys
  (:use)				;use nothing
  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  (:export
    ;; Resources
    allocate-resource
    clear-resource
    deallocate-resource
    defresource
    map-resource
    using-resource

    ;; Processes
    *multiprocessing-p*
    all-processes
    current-process
    destroy-process
    disable-process
    enable-process
    make-process
    process-interrupt
    process-name
    process-state
    process-wait
    process-wait-with-timeout
    process-whostate
    process-yield
    processp
    restart-process

    ;; Locks
    make-lock
    make-recursive-lock
    with-lock-held
    with-recursive-lock-held

    ;; Other synchronization
    atomic-decf
    atomic-incf
    without-scheduling

    ;; SETF*
    defgeneric*
    defmethod*
    setf*))




;; Define the CLIM package
(defpackage clim
  (:use)                                ;use nothing
  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  #+allegro (:implementation-packages
             :silica
             :clim-utils
             :clim-silica
             :clim-internals
             :postscript-clim
             :xm-silica)
  (:import-from clim-lisp
    and
    #-aclpc boolean
    character
    close
    complex
    float
    integer
    interactive-stream-p
    keyword
    member
    nil
    null
    number
    or
    pathname
    ratio
    rational
    real
    sequence
    stream-advance-to-column
    stream-clear-input
    stream-clear-output
    stream-element-type
    stream-finish-output
    stream-force-output
    stream-fresh-line
    stream-line-column
    stream-listen
    stream-peek-char
    stream-read-byte
    stream-read-char
    stream-read-char-no-hang
    stream-read-line
    stream-start-line-p
    stream-terpri
    stream-unread-char
    stream-write-byte
    stream-write-char
    stream-write-string
    string
    symbol
    t
    truename
    with-open-stream)

  (:export
    ;; Regions
    +everywhere+
    +nowhere+
    area
    areap
    coordinate
    ellipse
    ellipse-center-point
    ellipse-center-point*
    ellipse-end-angle
    ellipse-radii
    ellipse-start-angle
    ellipsep
    elliptical-arc
    elliptical-arc-p
    line
    line-end-point
    line-end-point*
    line-start-point
    line-start-point*
    linep
    make-ellipse
    make-ellipse*
    make-elliptical-arc
    make-elliptical-arc*
    make-line
    make-line*
    make-point
    make-polygon
    make-polygon*
    make-polyline
    make-polyline*
    make-rectangle
    make-rectangle*
    map-over-polygon-coordinates
    map-over-polygon-segments
    map-over-region-set-regions
    path
    pathp
    point
    point-position
    point-x
    point-y
    pointp
    polygon
    polygon-points
    polygonp
    polyline
    polyline-closed
    polylinep
    rectangle
    rectangle-edges*
    rectangle-height
    rectangle-max-point
    rectangle-max-x
    rectangle-max-y
    rectangle-min-point
    rectangle-min-x
    rectangle-min-y
    rectangle-size
    rectangle-width
    rectanglep
    region
    region-contains-position-p
    region-contains-region-p
    region-difference
    region-equal
    region-intersection
    region-intersects-region-p
    region-set
    region-set-p
    region-set-regions
    region-union
    regionp
    standard-ellipse
    standard-elliptical-arc
    standard-line
    standard-point
    standard-polygon
    standard-polyline
    standard-rectangle
    standard-region-difference
    standard-region-intersection
    standard-region-union

    ;; Bounding rectangles
    bounding-rectangle
    bounding-rectangle*
    bounding-rectangle-center
    bounding-rectangle-center*
    bounding-rectangle-height
    bounding-rectangle-max-x
    bounding-rectangle-max-y
    bounding-rectangle-min-x
    bounding-rectangle-min-y
    bounding-rectangle-p
    bounding-rectangle-position
    bounding-rectangle-size
    bounding-rectangle-width
    bounding-rectangle-left
    bounding-rectangle-top
    bounding-rectangle-right
    bounding-rectangle-bottom
    make-bounding-rectangle
    standard-bounding-rectangle
    with-bounding-rectangle*

    ;; Transformations
    +identity-transformation+
    compose-rotation-with-transformation
    compose-scaling-with-transformation
    compose-transformation-with-rotation
    compose-transformation-with-scaling
    compose-transformation-with-translation
    compose-transformations
    compose-translation-with-transformation
    even-scaling-transformation-p
    identity-transformation-p
    invert-transformation
    invertible-transformation-p
    make-3-point-transformation
    make-3-point-transformation*
    make-reflection-transformation
    make-reflection-transformation*
    make-rotation-transformation
    make-rotation-transformation*
    make-scaling-transformation
    make-scaling-transformation*
    make-transformation
    make-translation-transformation
    rectilinear-transformation-p
    reflection-transformation-p
    reflection-underspecified
    rigid-transformation-p
    scaling-transformation-p
    singular-transformation
    transform-distance
    transform-position
    transform-rectangle*
    transform-region
    transformation
    transformation-equal
    transformation-error
    transformation-underspecified
    transformationp
    translation-transformation-p
    untransform-distance
    untransform-position
    untransform-rectangle*
    untransform-region

    ;; Windowing substrate
    *default-server-path*
    +control-key+
    +hyper-key+
    +meta-key+
    +pointer-left-button+
    +pointer-middle-button+
    +pointer-right-button+
    +shift-key+
    +super-key+
    add-watcher
    allocate-medium
    basic-medium
    basic-pane
    basic-port
    basic-sheet
    bursting-input-queuer
    bury-sheet
    child-containing-position
    children-overlapping-rectangle*
    children-overlapping-region
    deallocate-medium
    define-sheet-class
    degraft-medium
    delegate-sheet-delegate
    delegate-sheet-input-mixin
    delete-watcher
    destroy-mirror
    destroy-port
    device-clipping-region
    device-event
    device-transformation
    disable-mirror
    dispatch-crossing-event
    dispatch-device-event
    dispatch-event
    display-medium
    distribute-device-event
    distribute-event
    enable-mirror
    engraft-medium
    enter-region
    event
    event-listen
    event-modifier-state
    event-peek
    event-read
    event-read-no-hang
    event-sheet
    event-timestamp
    event-type
    event-unread
    eventp
    exit-region
    fetch-clipping-region
    find-graft
    find-port
    focus-event
    focus-in-event
    focus-out-event
    graft
    graft-height
    graft-orientation
    graft-pixels-per-inch
    graft-pixels-per-millimeter
    graft-pixels-per-point
    graft-units
    graft-width
    graftp
    handle-event
    handle-repaint
    immediate-repainting-mixin
    immediate-sheet-input-mixin
    invalidate-cached-regions
    invalidate-cached-transformations
    invoking-input-contract
    key-modifier-state-match-p
    key-press-event
    key-release-event
    keyboard-event
    keyboard-event-character
    keyboard-event-key-name
    make-sheet
    make-standard-sheet
    map-over-grafts
    map-over-ports
    map-over-sheets
    map-over-sheets-containing-position
    map-over-sheets-overlapping-region
    map-sheet-position-to-child
    map-sheet-position-to-parent
    map-sheet-rectangle*-to-child
    map-sheet-rectangle*-to-parent
    medium
    medium-background
    medium-beep
    medium-clear-area
    medium-clipping-region
    medium-default-text-style
    medium-drawable
    medium-finish-output
    medium-force-output
    medium-foreground
    medium-ink
    medium-line-style
    medium-merged-text-style
    medium-sheet
    medium-text-style
    medium-transformation
    mediump
    mirrored-sheet-mixin
    move-and-resize-sheet
    move-sheet
    note-sheet-adopted
    note-sheet-degrafted
    note-sheet-disabled
    note-sheet-disowned
    note-sheet-enabled
    note-sheet-grafted
    note-sheet-gain-focus
    note-sheet-lose-focus
    note-sheet-region-changed
    note-sheet-transformation-changed
    permanent-medium-sheet-output-mixin
    pointer-boundary-event
    pointer-boundary-event-kind
    pointer-button-event
    pointer-button-hold-event
    pointer-button-press-event
    pointer-button-release-event
    pointer-click-event
    pointer-click-hold-event
    pointer-double-click-event
    pointer-enter-event
    pointer-event
    pointer-event-button
    pointer-event-native-x
    pointer-event-native-y
    pointer-event-pointer
    pointer-event-x
    pointer-event-y
    pointer-exit-event
    pointer-motion-event
    poll-pointer
    port
    port-alive-p
    port-keyboard-input-focus
    port-modifier-state
    port-name
    port-pointer
    port-properties
    port-server-path
    port-set-pointer-cursor
    port-type
    portp
    presentation-event
    primitive-sheet-output-mixin
    process-next-event
    queue-event
    queue-input
    queue-repaint
    raise-sheet
    realize-graft
    realize-mirror
    reorder-sheets
    repaint-sheet
    reset-watcher
    resize-sheet
    restart-port
    sheet
    sheet-adopt-child
    sheet-allocated-region
    sheet-ancestor-p
    sheet-child
    sheet-children
    sheet-delta-transformation
    sheet-device-region
    sheet-device-transformation
    sheet-direct-mirror
    sheet-disown-child
    sheet-enabled-children
    sheet-enabled-p
    sheet-event-queue
    sheet-grafted-p
    sheet-identity-transformation-mixin
    sheet-leaf-mixin
    sheet-medium
    sheet-mirror
    sheet-mirrored-ancestor
    sheet-multiple-child-mixin
    sheet-mute-input-mixin
    sheet-mute-output-mixin
    sheet-mute-repainting-mixin
    sheet-native-region
    sheet-native-region*
    sheet-native-transformation
    sheet-occluding-sheets
    sheet-parent
    sheet-parent-mixin
    sheet-permanently-enabled-mixin
    sheet-pointer-cursor
    sheet-region
    sheet-siblings
    sheet-single-child-mixin
    sheet-transformation
    sheet-transformation-mixin
    sheet-translation-mixin
    sheet-viewable-p
    sheet-y-inverting-transformation-mixin
    sheetp
    standard-event-distributor
    standard-graft
    standard-input-contract
    standard-repainting-mixin
    standard-sheet-input-mixin
    standard-sheet-output-mixin
    temporary-medium-sheet-output-mixin
    timer-event
    using-display-medium
    window-configuration-event
    window-event
    window-event-mirrored-sheet
    window-event-native-region
    window-event-region
    window-manager-delete-event
    window-manager-event
    window-repaint-event
    with-graft-locked
    with-output-protection
    with-port-locked
    with-sheet-medium
    with-sheet-medium-bound

    ;; Drawing options
    contrasting-dash-patterns-limit
    invoke-with-drawing-options
    line-style
    line-style-cap-shape
    line-style-dashes
    line-style-joint-shape
    line-style-p
    line-style-thickness
    line-style-unit
    make-contrasting-dash-patterns
    make-line-style
    standard-line-style
    with-drawing-options
    with-first-quadrant-coordinates
    with-local-coordinates
    with-rotation
    with-scaling
    with-translation

    ;; Text styles
    *default-text-style*
    *undefined-text-style*
    invoke-with-text-style
    make-device-font-text-style
    make-text-style
    merge-text-styles
    parse-text-style
    standard-text-style
    text-size
    text-style
    text-style-ascent
    text-style-components
    text-style-descent
    text-style-face
    text-style-family
    text-style-fixed-width-p
    text-style-height
    text-style-mapping
    text-style-mapping-exists-p
    text-style-p
    text-style-size
    text-style-width
    with-text-face
    with-text-family
    with-text-size
    with-text-style

    ;; Graphics
    allocate-pixmap
    copy-area
    copy-from-pixmap
    copy-to-pixmap
    deallocate-pixmap
    draw-arrow
    draw-arrow*
    draw-bezier-curve
    draw-bezier-curve*
    draw-circle
    draw-circle*
    draw-ellipse
    draw-ellipse*
    draw-line
    draw-line*
    draw-lines
    draw-lines*
    draw-oval
    draw-oval*
    draw-pixmap
    draw-pixmap*
    draw-point
    draw-point*
    draw-points
    draw-points*
    draw-polygon
    draw-polygon*
    draw-rectangle
    draw-rectangle*
    draw-rectangles
    draw-rectangles*
    draw-text
    draw-text*
    medium-copy-area
    medium-draw-bezier-curve*
    medium-draw-character*
    medium-draw-ellipse*
    medium-draw-line*
    medium-draw-lines*
    medium-draw-pixmap*
    medium-draw-point*
    medium-draw-points*
    medium-draw-polygon*
    medium-draw-rectangle*
    medium-draw-rectangles*
    medium-draw-string*
    medium-draw-text*
    pixmap-depth
    pixmap-height
    pixmap-width
    with-output-to-pixmap
    with-medium-state-cached

    ;; Colors
    +background-ink+
    +flipping-ink+
    +foreground-ink+
    +transparent-ink+
    color
    color-ihs
    color-not-found
    color-rgb
    colorp
    contrasting-inks-limit
    design
    designp
    dynamic-color-color
    find-named-color
    layered-color
    layered-color-color
    make-contrasting-inks
    make-dynamic-color
    make-flipping-ink
    make-gray-color
    make-ihs-color
    make-layered-color-set
    make-opacity
    make-rgb-color
    opacity
    opacity-value
    opacityp
    with-delayed-recoloring

    ;; Designs
    compose-in
    compose-out
    compose-over
    draw-design
    draw-pattern*
    make-pattern
    make-rectangular-tile
    make-stencil
    pattern-height
    pattern-width
    pattern-array
    pattern-designs

    ;; Palettes
    add-colors-to-palette
    color-stream-p
    find-closest-matching-color
    frame-manager-palette
    frame-palette
    make-palette
    palette
    palette-color-p
    palette-dynamic-p
    palette-full
    palette-full-color
    palette-full-palette
    palettep
    port-default-palette
    remove-colors-from-palette
    use-other-color
    *use-closest-color*

    ;; Extended output
    *default-cursor-color*
    beep
    cursor
    cursor-active
    cursor-color
    cursor-focus
    cursor-position
    cursor-sheet
    cursor-state
    cursor-visibility
    cursorp
    display-cursor
    extended-output-stream
    extended-output-stream-p
    note-cursor-change
    sheet-buffering-output-p
    standard-extended-output-stream
    standard-output-stream
    standard-text-cursor
    stream-advance-to-column
    stream-baseline
    stream-character-width
    stream-clear-output
    stream-cursor-position
    stream-end-of-line-action
    stream-end-of-page-action
    stream-finish-output
    stream-force-output
    stream-fresh-line
    stream-increment-cursor-position
    stream-line-column
    stream-line-height
    stream-start-line-p
    stream-string-output-size
    stream-string-width
    stream-terpri
    stream-text-cursor
    stream-text-margin
    stream-vertical-spacing
    stream-write-char
    stream-write-string
    with-end-of-line-action
    with-end-of-page-action
    with-output-buffered
    with-room-for-graphics

    ;; Output recording
    add-character-output-to-text-record
    add-output-record
    add-string-output-to-text-record
    clear-output-record
    copy-textual-output-history
    delete-output-record
    displayed-output-record
    displayed-output-record-ink
    displayed-output-record-p
    erase-output-record
    graphics-displayed-output-record
    graphics-displayed-output-record-p
    highlight-output-record
    invoke-with-new-output-record
    invoke-with-output-recording-options
    invoke-with-output-to-output-record
    make-design-from-output-record
    map-over-output-records
    map-over-output-records-containing-position
    map-over-output-records-overlapping-region
    output-record
    output-record-children
    output-record-count
    output-record-end-cursor-position
    output-record-hit-detection-rectangle*
    output-record-p
    output-record-parent
    output-record-position
    output-record-refined-position-test
    output-record-start-cursor-position
    output-recording-stream
    output-recording-stream-p
    r-tree-output-history
    r-tree-output-record
    recompute-extent-for-changed-child
    recompute-extent-for-new-child
    replay
    replay-output-record
    standard-output-recording-stream
    standard-sequence-output-history
    standard-sequence-output-record
    standard-tree-output-history
    standard-tree-output-record
    stream-add-character-output
    stream-add-output-record
    stream-add-string-output
    stream-close-text-output-record
    stream-current-output-record
    stream-drawing-p
    stream-output-history
    stream-output-history-mixin
    stream-replay
    stream-recording-p
    stream-text-output-record
    text-displayed-output-record
    text-displayed-output-record-p
    text-displayed-output-record-string
    tree-recompute-extent
    with-new-output-record
    with-output-recording-options
    with-output-to-output-record

    ;; Table formatting
    adjust-item-list-cells
    adjust-multiple-columns
    adjust-table-cells
    cell-align-x
    cell-align-y
    cell-min-height
    cell-min-width
    cell-output-record
    cell-output-record-p
    column-output-record
    column-output-record-p
    format-items
    formatting-cell
    formatting-column
    formatting-item-list
    formatting-row
    formatting-table
    item-list-output-record
    item-list-output-record-p
    map-over-item-list-cells
    map-over-row-cells
    map-over-table-elements
    row-output-record
    row-output-record-p
    standard-cell-output-record
    standard-column-output-record
    standard-item-list-output-record
    standard-row-output-record
    standard-table-output-record
    table-output-record
    table-output-record-p

    ;; Graph formatting
    *default-generation-separation*
    *default-within-generation-separation*
    define-graph-type
    format-graph-from-root
    format-graph-from-roots
    generate-graph-nodes
    graph-node-children
    graph-node-object
    graph-node-output-record
    graph-node-output-record-p
    graph-node-parents
    graph-output-record
    graph-output-record-p
    graph-root-nodes
    layout-graph-edges
    layout-graph-nodes
    standard-graph-node-output-record
    standard-graph-output-record

    ;; Bordered output
    define-border-type
    surrounding-output-with-border

    ;; Text formatting
    filling-output
    format-textual-list
    indenting-output

    ;; Incremental redisplay
    augment-draw-set
    cache-output-record
    compute-difference-set
    compute-new-output-records
    decache-child-output-record
    find-cached-output-record
    find-child-output-record
    incremental-redisplay
    match-output-records
    note-output-record-child-changed
    output-record-cache-value
    output-record-contents-ok
    output-record-displayer
    output-record-fixed-position
    output-record-unique-id
    propagate-output-record-changes
    propagate-output-record-changes-p
    recompute-contents-ok
    redisplay
    redisplay-output-record
    redisplayable-stream-p
    standard-updating-output-record
    stream-redisplaying-p
    updating-output
    updating-output-record
    updating-output-record-p

    ;; Extended input
    *abort-gestures*
    *accelerator-gestures*
    *asynchronous-abort-gestures*
    *input-wait-handler*
    *input-wait-test*
    *pointer-button-press-handler*
    abort-gesture
    abort-gesture-event
    accelerator-gesture
    accelerator-gesture-event
    accelerator-gesture-numeric-argument
    add-gesture-name
    define-gesture-name
    delete-gesture-name
    drag-output-record
    dragging-output
    event-matches-gesture-name-p
    extended-input-stream
    extended-input-stream-p
    gesture-name-button-and-modifiers
    gesture-name-keysym-and-modifiers
    gesture-processing-handler
    make-modifier-state
    modifier-state-matches-gesture-name-p
    pointer
    pointer-button-state
    pointer-cursor
    pointer-native-position
    pointer-position
    pointer-sheet
    pointerp
    read-gesture
    standard-extended-input-stream
    standard-input-stream
    standard-pointer
    stream-clear-input
    stream-input-buffer
    stream-input-wait
    stream-listen
    stream-peek-char
    stream-pointer-position
    stream-pointers
    stream-primary-pointer
    stream-read-char
    stream-read-char-no-hang
    stream-read-gesture
    stream-read-line
    stream-restore-input-focus
    stream-set-input-focus
    stream-unread-char
    stream-unread-gesture
    tracking-pointer
    unread-gesture
    with-input-focus
    with-pointer-grabbed

    ;; Presentation types
    *input-context*
    *null-presentation*
    +check-box-view+
    +gadget-dialog-view+
    +gadget-menu-view+
    +gadget-view+
    +list-pane-view+
    +option-pane-view+
    +pointer-documentation-view+
    +push-button-view+
    +radio-box-view+
    +slider-view+
    +text-editor-view+
    +text-field-view+
    +textual-dialog-view+
    +textual-menu-view+
    +textual-view+
    +toggle-button-view+
    accept
    accept-from-string
    accept-1
    accept-method
    accept-present-default
    accept-present-default-method
    apply-presentation-generic-function
    and
    blank-area
    boolean
    call-presentation-menu
    call-presentation-translator
    character
    check-box-view
    class-presentation-type-name
    completion
    complex
    decode-indirect-view
    default-describe-presentation-type
    define-default-presentation-method
    define-drag-and-drop-translator
    define-presentation-action
    define-presentation-generic-function
    define-presentation-method
    define-presentation-to-command-translator
    define-presentation-translator
    define-presentation-type
    define-presentation-type-abbreviation
    describe-presentation-type
    describe-presentation-type-method
    document-presentation-translator
    expand-presentation-type-abbreviation
    expand-presentation-type-abbreviation-1
    expression
    find-applicable-translators
    find-innermost-applicable-presentation
    find-presentation-translators
    find-presentation-type-class
    float
    form
    frame-document-highlighted-presentation
    funcall-presentation-generic-function
    gadget-dialog-view
    gadget-menu-view
    gadget-view
    highlight-applicable-presentation
    highlight-presentation
    highlight-presentation-method
    integer
    input-context-type
    keyword
    list-pane-view
    make-presentation-type-specifier
    map-over-presentation-type-supertypes
    map-over-presentation-type-supertypes-method
    member
    member-alist
    member-sequence
    nil
    null
    null-or-type
    number
    option-pane-view
    or
    pathname
    pointer-documentation-view
    present
    present-method
    present-to-string
    presentation
    presentation-default-preprocessor
    presentation-default-preprocessor-method
    presentation-matches-context-type
    presentation-modifier
    presentation-object
    presentation-refined-position-test
    presentation-refined-position-test-method
    presentation-single-box
    presentation-subtypep
    presentation-subtypep-method
    presentation-type
    presentation-type-direct-supertypes
    presentation-type-history
    presentation-type-history-method
    presentation-type-of
    presentation-type-name
    presentation-type-options
    presentation-type-parameters
    presentation-type-specifier-p
    presentation-type-specifier-p-method
    presentation-typep
    presentation-typep-method
    presentationp
    prompt-for-accept
    prompt-for-accept-1
    push-button-view
    radio-box-view
    ratio
    rational
    real
    sequence
    sequence-enumerated
    set-highlighted-presentation
    slider-view
    standard-presentation
    stream-accept
    stream-default-view
    stream-present
    string
    subset
    subset-alist
    subset-completion
    subset-sequence
    symbol
    t
    test-presentation-translator
    text-editor-view
    text-field-view
    textual-dialog-view
    textual-menu-view
    textual-view
    throw-highlighted-presentation
    toggle-button-view
    token-or-type
    type-or-string
    unhighlight-highlighted-presentation
    view
    viewp
    with-input-context
    with-output-as-presentation
    with-presentation-type-decoded
    with-presentation-type-options
    with-presentation-type-parameters
    with-presentations-to-string

    ;; Presentation histories and kill rings
    do-history-elements
    history-top-element
    make-presentation-type-history
    pop-history-element
    push-history-element
    presentation-history-element-object
    presentation-history-element-type
    reset-history
    yank-from-history
    yank-next-from-history

    ;; Input editing and completion
    *activation-gestures*
    *completion-gestures*
    *delimiter-gestures*
    *help-gestures*
    *possibilities-gestures*
    *standard-activation-gestures*
    activation-gesture-p
    add-input-editor-command
    complete-from-generator
    complete-from-possibilities
    complete-input
    completing-from-suggestions
    delimiter-gesture-p
    erase-input-buffer
    immediate-rescan
    input-editing-stream
    input-editing-stream-p
    input-editor-buffer
    input-editor-format
    input-not-of-required-type
    interactive-stream-p
    presentation-replace-input
    queue-rescan
    read-token
    redraw-input-buffer
    replace-input
    rescan-if-necessary
    reset-scan-pointer
    simple-parse-error
    standard-input-editing-stream
    stream-insertion-pointer
    stream-process-gesture
    stream-read-gesture
    stream-rescanning-p
    stream-scan-pointer
    stream-unread-gesture
    suggest
    with-accept-help
    with-activation-gestures
    with-delimiter-gestures
    with-input-editing
    with-input-editor-typeout
    write-token

    ;; Menus
    draw-standard-menu
    frame-manager-menu-choose
    menu-choose
    menu-choose-from-drawer
    menu-item
    menu-item-display
    menu-item-options
    menu-item-value
    print-menu-item
    with-menu

    ;; Dialogs
    accept-values
    accept-values-command-button
    accept-values-pane
    accept-values-pane-displayer
    accept-values-resynchronize
    accepting-values
    display-exit-boxes
    frame-manager-dialog-view
    invoke-accept-values-command-button
    with-aligned-prompts

    ;; Command processor
    *command-argument-delimiters*
    *command-dispatchers*
    *command-name-delimiters*
    *command-parser*
    *command-unparser*
    *numeric-argument-marker*
    *partial-command-parser*
    *unsupplied-argument-marker*
    accept-values-command-parser
    add-command-to-command-table
    add-keystroke-to-command-table
    add-menu-item-to-command-table
    add-presentation-translator-to-command-table
    command
    command-accessible-in-command-table-p
    command-already-present
    command-arguments
    command-line-command-parser
    command-line-command-unparser
    command-line-name-for-command
    command-line-read-remaining-arguments-for-partial-command
    command-menu-item-options
    command-menu-item-type
    command-menu-item-value
    command-name
    command-name-from-symbol
    command-not-accessible
    command-not-present
    command-or-form
    command-present-in-command-table-p
    command-table
    command-table-already-exists
    command-table-complete-input
    command-table-error
    command-table-inherit-from
    command-table-name
    command-table-not-found
    command-table-p
    define-command
    define-command-table
    display-command-table-menu
    do-command-table-inheritance
    find-command-from-command-line-name
    find-command-table
    find-keystroke-item
    find-menu-item
    find-presentation-translator
    global-command-table
    lookup-keystroke-command-item
    lookup-keystroke-item
    make-command-table
    map-over-command-table-commands
    map-over-command-table-keystrokes
    map-over-command-table-menu-items
    map-over-command-table-names
    map-over-command-table-translators
    menu-choose-command-from-command-table
    menu-command-parser
    menu-read-remaining-arguments-for-partial-command
    partial-command-p
    read-command
    read-command-using-keystrokes
    remove-command-from-command-table
    remove-keystroke-from-command-table
    remove-menu-item-from-command-table
    remove-presentation-translator-from-command-table
    standard-command-table
    substitute-numeric-argument-marker
    user-command-table
    with-command-table-keystrokes

    ;; Application frames and frame managers
    *application-frame*
    *default-frame-manager*
    *pointer-documentation-output*
    adopt-frame
    application-frame
    application-frame-p
    application-pane
    bury-frame
    client-setting
    command-enabled
    command-menu-pane
    default-frame-top-level
    define-application-frame
    destroy-frame
    disable-frame
    disown-frame
    display-command-menu
    display-invalid-queries
    enable-frame
    execute-frame-command
    execute-command-in-frame
    find-application-frame
    find-frame-manager
    find-pane-for-frame
    find-pane-named
    frame-all-layouts
    frame-calling-frame
    frame-command-table
    frame-current-layout
    frame-current-panes
    frame-document-highlighted-presentation
    frame-drag-and-drop-feedback
    frame-drag-and-drop-highlighting
    frame-error-output
    frame-exit
    frame-exit-frame
    frame-find-innermost-applicable-presentation
    frame-input-context-button-press-handler
    frame-maintain-presentation-histories
    frame-manager
    frame-manager-clear-progress-note
    frame-manager-default-exit-boxes
    frame-manager-display-help
    frame-manager-display-pointer-documentation
    frame-manager-display-pointer-documentation-string
    frame-manager-display-progress-note
    frame-manager-exit-box-labels
    frame-manager-frames
    frame-manager-notify-user
    frame-manager-pointer-documentation-stream
    frame-manager-print-file  ; jpm
    frame-manager-select-file
    frame-name
    frame-named-panes
    frame-pane
    frame-pane-name
    frame-panes
    frame-pointer-documentation-output
    frame-pretty-name
    frame-properties
    frame-query-io
    frame-replay
    frame-standard-input
    frame-standard-output
    frame-state
    frame-top-level-sheet
    frame-menu-translator-documentation
    frame-pointer-button-documentation
    frame-modifier-key-documentation
    generate-panes
    get-frame-pane
    interactor-pane
    layout-frame
    make-application-frame
    map-over-frames
    note-command-disabled
    note-command-enabled
    note-frame-deiconified
    note-frame-disabled
    note-frame-enabled
    note-frame-iconified
    note-frame-layout-changed
    notify-user
    pane-frame
    pane-name
    pane-needs-redisplay
    panes-need-redisplay
    pointer-documentation-pane
    position-sheet-carefully
    position-sheet-near-pointer
    print-file				; jpm
    raise-frame
    read-frame-command
    reconfigure-frame
    redisplay-frame-pane
    redisplay-frame-panes
    reset-frame
    run-frame-top-level
    select-file
    shrink-frame
    size-frame-from-contents
    standard-application-frame
    standard-frame-manager
    window-clear
    window-erase-viewport
    window-refresh
    window-viewport
    window-viewport-position
    with-application-frame
    with-frame-manager

    ;; Meta-frames, aka activities
    *activity*
    activity
    activity-frame
    activity-frame-window-close
    activity-frame-window-select
    activity-quit
    destroy-activity
    frame-activity
    select-activity-active-frame
    start-application-frame
    start-initial-application-frame
    stop-application-frame

    ;; Progress notes
    *current-progress-note*
    dolist-noting-progress
    dotimes-noting-progress
    note-progress
    note-progress-in-phases
    noting-progress
    progress-note-name

    ;; Panes
    +fill+
    allocate-space
    bulletin-board-pane
    bulletin-board
    border-pane
    bordering
    change-space-requirements
    changing-space-requirements
    clim-stream-pane
    clim-stream-sheet
    compose-space
    hbox-pane
    horizontal-divider
    horizontally
    hrack-pane
    label-pane
    labelling
    lowering
    make-clim-application-pane
    make-clim-interactor-pane
    make-clim-stream-pane
    make-pane
    make-pane-1
    make-space-requirement
    note-space-requirements-changed
    note-viewport-position-changed
    outlined-pane
    outlining
    pane
    pane-background
    pane-foreground
    pane-scroller
    pane-text-style
    pane-viewport
    pane-viewport-region
    panep
    raising
    restraining
    restraining-pane
    scroll-extent
    scroller-pane
    scrolling
    space-requirement
    space-requirement-height
    space-requirement-max-height
    space-requirement-max-width
    space-requirement-min-height
    space-requirement-min-width
    space-requirement-width
    spacing
    spacing-pane
    table-pane
    tabling
    text-stream-pane
    top-level-sheet
    vbox-pane
    vertical-divider
    vertically
    viewport
    viewport-viewport-region
    vrack-pane
    with-look-and-feel-realization

    ;; Gadgets
    action-gadget
    activate-callback
    activate-gadget
    armed-callback
    basic-gadget
    check-box
    check-box-current-selection
    check-box-pane
    check-box-selections
    command-callback
    deactivate-gadget
    disarmed-callback
    drag-callback
    gadget
    gadget-activate-callback
    gadget-active-p
    gadget-alignment
    gadget-armed-callback
    gadget-client
    gadget-columns
    gadget-current-selection
    gadget-disarmed-callback
    gadget-editable-p
    gadget-id
    gadget-indicator-type
    gadget-label
    gadget-label-align-x
    gadget-label-align-y
    gadget-label-text-style
    gadget-max-value
    gadget-min-value
    gadget-orientation
    gadget-output-record
    gadget-range
    gadget-range*
    gadget-spacing
    gadget-show-value-p
    gadget-value
    gadget-value-changed-callback
    gadget-word-wrap
    gadgetp
    labelled-gadget-mixin
    list-pane
    list-pane-mode
    menu-bar
    menu-bar-command-table
    menu-bar-text-style
    menu-button
    menu-button-pane
    note-gadget-activated
    note-gadget-deactivated
    option-pane
    oriented-gadget-mixin
    push-button
    push-button-pane
    #+(or aclpc acl86win32) push-button-show-as-default-p
    push-button-show-as-default
    radio-box
    radio-box-current-selection
    radio-box-pane
    radio-box-selections
    scroll-bar
    scroll-bar-drag-callback
    scroll-bar-scroll-to-bottom-callback
    scroll-bar-scroll-to-top-callback
    scroll-bar-scroll-down-line-callback
    scroll-bar-scroll-up-line-callback
    scroll-bar-scroll-down-page-callback
    scroll-bar-scroll-up-page-callback
    scroll-to-bottom-callback
    scroll-to-top-callback
    scroll-down-line-callback
    scroll-up-line-callback
    scroll-down-page-callback
    scroll-up-page-callback
    scroll-bar
    scroll-bar-pane
    scroll-bar-size
    set-gadget-items
    set-gadget-name-key
    set-gadget-test
    set-gadget-value-key
    slider
    slider-decimal-places
    slider-pane
    text-editor
    text-editor-pane
    text-field
    text-field-pane
    toggle-button
    toggle-button-indicator-type
    toggle-button-pane
    value-changed-callback
    value-gadget
    with-output-as-gadget
    with-radio-box

    ;; Encapsulating streams
    *original-stream*
    encapsulating-stream
    encapsulating-stream-p
    encapsulating-stream-stream
    standard-encapsulating-stream

    ;; PostScript
    new-page
    with-output-to-postscript-stream)

  (:export
   read-bitmap-file
   *bitmap-search-path*
   make-pattern-from-bitmap-file
   make-pattern-from-pixmap
   make-bitmap-file-from-pattern
   write-bitmap-file
   compute-filter-for-bitmap-format
   )

  ;; Primary colors
  (:export
    +red+
    +green+
    +blue+
    +cyan+
    +magenta+
    +yellow+
    +black+
    +white+)

  ;; Need to export these since not everybody hacks SETF* yet
  (:export
    bounding-rectangle-set-position
    cursor-set-position
    output-record-set-position
    output-record-set-start-cursor-position
    output-record-set-end-cursor-position
    pointer-set-native-position
    pointer-set-position
    stream-set-cursor-position
    stream-set-pointer-position
    window-set-viewport-position)

  ;; Some extensions until we decide what to do...
  (:export
    +iconic-view+
    catch-abort-gestures
    convert-from-absolute-to-relative-coordinates
    convert-from-ancestor-to-descendant-coordinates
    convert-from-descendant-to-ancestor-coordinates
    convert-from-relative-to-absolute-coordinates
    convert-to-stream-coordinates
    draw-regular-polygon
    draw-regular-polygon*
    draw-triangle
    draw-triangle*
    drawing-surface-to-viewport-coordinates
    fix-coordinate
    fix-coordinates
    hierarchical-menu-choose
    iconic-view
    open-window-stream
    pointer-input-rectangle
    pointer-input-rectangle*
    pointer-place-rubber-band-line*
    translate-coordinates
    translate-positions
    viewport-to-drawing-surface-coordinates
    window-children
    window-expose
    window-inside-bottom
    window-inside-edges
    window-inside-height
    window-inside-left
    window-inside-right
    window-inside-size
    window-inside-top
    window-inside-width
    window-label
    window-label-size
    window-margins
    window-parent
    window-root
    window-set-inside-size
    window-stack-on-bottom
    window-stack-on-top
    window-stream-p
    window-visibility
    windowp
    window-top-level-window))

#+allegro
(excl:ics-target-case
(:+ics

(defpackage clim
  (:use)
  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  ;; should these all be exported from the clim package?

  (:export
   jie-begin-kanji-conversion
   jie-get-kanji
   jie-end-kanji-conversion
   kanji-server-p
   kanji-server-type
   kanji-server-path
   kanji-server
   map-over-kanji-servers
   find-kanji-server
   destroy-kanji-server
   basic-kanji-server
   *default-kanji-server-path*))

)) ;; ics-target-case



;; Now define all of the implementation packages
(defpackage clim-utils
  #+allegro (:implementation-packages :clim-utils :clim-silica
			    :clim-internals :xt-silica)
  (:use	clim-lisp clim-sys clim)

  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  #+allegro (:import-from excl
    arglist)

  (:export
    arglist

    ;; From DEFUN
    *keyword-package*
    extract-declarations

    ;; From UTILITIES
    boolean
    collect
    def-property-slot-accessors
    def-property-slot-macros
    define-unimplemented-protocol-method
    ignore-errors
    make-setf-function-name
    safe-slot-value
    unimplemented warn-obsolete
    with-collection
    with-fast-vector-references
    with-gensyms

    ;; From LISP-UTILITIES
    *end-of-file-marker*
    +largest-coordinate+
    bind-to-list
    canonicalize-and-match-lambda-lists
    clause
    compile-time-property
    convert-to-device-coordinates
    convert-to-device-distances
    copy-vector-portion
    define-dynamic-extent-args
    define-group
    define-keywords
    defun-inline
    defun-property
    do-delimited-substrings
    dorest
    doseq
    dovector
    end-of-file-marker
    evacuate-list
    fast-abs
    find-class-that-works
    fintern
    package-fintern
    flatten-arglist
    follow-synonym-stream
    funcallable-p
    gensymbol
    get-compile-time-local-property
    ignore-arglist
    lambda-list-variables-used-in-body
    letf-globally
    letf-globally-if
    make-pass-on-arglist
    minf maxf minf-or maxf-or
    once-only
    ordinary-char-p
    parameter-specifier-keyword
    push-unique
    remove-keywords
    remove-word-from-string
    repeat
    roundf
    simple-vector-insert-element
    simple-vector-push-extend
    standard-io-environment-vars-and-vals
    string-to-foreign
    time-elapsed-p
    trap-on-error
    whitespace-char-p
    with-compile-time-local-property
    with-keywords-removed
    with-stack-array
    with-stack-copy-of-list
    with-stack-list
    with-stack-list*
    with-standard-io-environment
    with-warnings-for-definition
    writing-clauses

    ;; From CLIM;TEMP-STRINGS
    with-temporary-string
    with-temporary-substring

    ;; From SILICA;TEXT-STYLE
    char-character-set-and-index
    diacritic-char-p

    ;; From CLOS
    define-constructor
    define-constructor-using-prototype-instance

    ;; From QUEUE
    locking-queue
    make-queue
    make-locking-queue
    map-over-queue
    queue
    queue-contents-list
    queue-contents-type
    queue-empty-p
    queue-flush
    queue-full-p
    queue-get
    queue-last
    queue-length
    queue-next
    queue-pop
    queue-push
    queue-put
    queue-size
    queue-unget
    with-queue-locked

    ;; From TIMERS
    add-timer
    delete-timer
    make-timer

    ;; From PROTOCOLS, DEFPROTOCOL, and CLIM-STREAMS
    *outer-self*
    define-protocol-class
    define-slot-trampoline-template
    define-trampoline-template
    defoperation
    defprotocol
    defrole
    encapsulating-stream
    find-protocol
    find-role
    generate-trampolines
    operation
    operation-extra-args
    operation-name
    operation-required-args
    operation-specs
    protocol
    protocol-name
    protocol-operations
    protocol-roles
    role
    role-slots
    stream

    ;; From CLIM-MACROS
    default-input-stream
    default-output-stream
    default-query-stream
    with-identity-transformation

    ;; From TRANSFORMATIONS
    identity-transformation
    standard-transformation
    translation-transformation

    ;; From REGIONS
    left top right bottom
    everywhere
    fix-rectangle
    make-rectangle-set
    make-region-difference
    make-region-intersection
    make-region-union
    nowhere
    opacity
    standard-opacity
    standard-rectangle-set

    ;; Additional bounding rectangle stuff
    bounding-rectangle-edges-equal
    bounding-rectangle-position-difference
    bounding-rectangle-position-equal
    bounding-rectangle-set-edges
    bounding-rectangle-set-size
    bounding-rectangle-shift-position
    bounding-rectangle-size-equal
    position-difference

    ;; LTRBs
    ltrb-contains-ltrb-p
    ltrb-contains-position-p
    ltrb-difference
    ltrb-equals-ltrb-p
    ltrb-intersection
    ltrb-overlaps-ltrb-p
    ltrb-size-equal
    ltrb-union
    ltrb-well-formed-p

    ;; Some random geometry
    2pi
    2x2-singular-value-decomposition
    angle-between-angles-p
    degrees->radians
    elliptical-arc-box
    pi-single-float
    pi/2
    point-close-to-line-p
    point-inside-ellipse-p
    point-on-thick-ellipse-p
    radians->degrees

    ;; From BASE-DESIGNS and DESIGNS
    *all-palettes*
    allocate-color
    basic-palette
    color-luminosity
    composite-in
    composite-out
    composite-over
    contrasting-ink
    contrasting-ink-index
    convert-ihs-to-rgb
    convert-rgb-to-ihs
    deallocate-color
    decode-flipping-ink
    decode-pattern
    decode-rectangular-tile
    decode-tile-as-stipple
    device-color
    device-color-color
    device-color-pixel
    device-color-palette
    make-device-color
    dynamic-color
    dynamic-color-palettes
    flipping-ink
    flipping-ink
    gray-color
    gray-color-luminosity
    ihs-color
    layered-color-layers
    layered-color-set
    layered-color-set-layers
    layered-color-set-dynamic-array
    make-color-for-contrasting-ink
    make-design-from-output-record
    make-flipping-ink
    make-gray-color-for-contrasting-ink
    map-over-layered-colors
    palette-color-cache
    palette-delayed-recolors
    palette-dynamic-color-cache
    palette-layered-color-cache
    palette-full-error
    pattern
    rectangular-tile
    rgb-color
    stencil
    stencil-array
    update-palette-entry
    update-palette-entries

    ;; Others
    *modifier-keys*
    button-index-name
    command-name-from-symbol
    modifier-key-index
    modifier-key-index-name))

#+(or aclpc acl86win32)
(eval-when (compile load eval)
 (intern '#:non-dynamic-extent (find-package :clim-utils)))

(defpackage clim-silica
   (:nicknames silica pyrex)
   #+allegro (:implementation-packages :clim-silica :clim-internals :xt-silica)
  (:use	clim-lisp clim-sys clim clim-utils)

  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  (:shadowing-import-from clim-utils
    defun
    flet labels
    defgeneric defmethod
    dynamic-extent)

  (:export
    *all-drawing-options*
    *default-pane-background*
    *default-pane-foreground*
    *modifier-keys*
    *null-text-style*
    *pointer-buttons*
    *ports*
    *standard-character-set*
    *all-character-sets*
    #+(or aclpc acl86win32) *undefined-text-style*
    +highlighting-line-style+
    activate-gadget-event
    add-sheet-callbacks
    all-drawing-options-lambda-list
    allocate-event
    armed-gadget-event
    basic-pixmap-medium
    bury-mirror
    canvas
    change-scroll-bar-values
    change-space-requirements-to
    change-space-requirements-to-default
    char-width
    choose-from-pull-down-menu
    clear-space-requirement-cache
    clear-space-requirement-caching-in-ancestors
    clear-space-requirement-caches-in-tree
    client-overridability-mixin
    compute-gadget-label-size
    compute-list-pane-selected-items
    compute-menu-bar-pane
    compute-symmetric-value
    compute-text-x-adjustment
    compute-text-y-adjustment
    copy-event
    deallocate-event
    default-space-requirements
    define-character-face
    define-character-face-added-mappings
    define-character-face-class
    define-display-device
    define-graphics-generic
    define-graphics-method
    define-text-style-mappings
    define-text-style-mappings-1
    disarmed-gadget-event
    distribute-event-1
    drag-gadget-event
    draw-gadget-label
    find-port-type
    fit-region*-in-region*
    focus-gadget
    focus-in-gadget-event
    focus-out-gadget-event
    frame-background
    frame-foreground
    frame-text-style
    frame-input-buffer
    frame-manager-matches-options-p
    frame-manager-note-pretty-name-changed
    frame-shell
    frame-user-specified-position-p
    frame-user-specified-size-p
    frame-wrapper
    gadget-event
    gadget-focus-out-callback
    gadget-focus-in-callback
    gadget-lines
    gadget-supplied-scrolling
    gadget-visible-items
    generic-label-pane
    generic-list-pane
    generic-option-pane
    generic-scroller-pane
    get-drawing-function-description
    get-sheet-resources
    graft-mm-height
    graft-mm-width
    graft-pixel-height
    graft-pixel-width
    grid-pane
    inhibit-updating-scroll-bars
    initialize-pull-down-menu
    invoke-callback-function
    invoke-with-menu-as-popup
    invoke-with-mouse-grabbed-in-window
    invoke-with-output-to-pixmap
    invoke-with-pointer-grabbed
    invoke-with-sheet-medium
    label-button-pane
    layout-mixin
    line-editor-pane
    list-pane-selected-item-p
    make-frame-manager
    make-medium
    make-pane-arglist
    make-pane-class
    make-pixmap-medium
    make-pull-down-menu
    map-endpoint-sequence
    map-position-sequence
    medium-+y-upward-p
    medium-draw-transformed-rectangles*
    medium-merged-text-style-valid
    medium-text-bounding-box
    menu-bar-button
    menu-bar-pane
    merged-text-style
    mirror->sheet
    mirror-edges*
    mirror-inside-edges*
    mirror-native-edges*
    mirror-inside-region*
    mirror-region
    mirror-region*
    mirror-region-updated
    mirror-visible-p
    modifier-keysym
    move-focus-to-gadget
    port-move-focus-to-gadget
    non-drawing-option-keywords
    note-layout-mixin-region-changed
    note-sheet-tree-grafted
    pane-contents
    parse-gesture-spec
    pixmap
    pixmap-from-menu-item
    pixmap-sheet
    pixmap-stream
    pointer-x-position
    pointer-y-position
    pointer-native-x-position
    pointer-native-y-position
    popup-menu-sheet
    port-allocate-pixmap
    port-canonical-gesture-specs
    port-canonicalize-gesture-spec
    port-deallocate-pixmap
    port-display
    port-draw-cursor
    port-event-loop
    port-event-wait
    port-glyph-for-character
    port-graft-class
    port-grafts
    port-input-focus-selection
    port-invalidate-gesture-specs
    port-invoke-with-pointer-grabbed
    port-mirror->sheet-table
    port-move-frame
    port-resize-frame
    port-remove-all-pointer-grabs
    port-note-cursor-change
    port-note-frame-adopted
    port-note-gadget-activated
    port-note-gadget-deactivated
    port-process
    port-set-pointer-position
    port-set-sheet-pointer-cursor
    port-set-sheet-grabbed-pointer-cursor
    port-terminated
    port-trace-thing
    #+(or aclpc acl86win32) port-undefined-text-style
    process-event-locally
    pull-down-menu
    pull-down-menu-button
    pull-down-menu-frame
    radio-button-pane
    raise-mirror
    #+(or aclpc acl86win32) scroll-bar-size
    scroll-bar-shaft-pane
    scroll-bar-target-pane
    #+(or aclpc acl86win32) scroll-bar-value
    scroll-bar-value-changed-callback
    scrollable-pane
    scroller-pane-gadget-supplies-scrolling-p
    scroller-pane-horizontal-scroll-bar
    scroller-pane-vertical-scroll-bar
    scroller-pane-drag-scroll
    scroller-pane-scroll-bar-policy
    set-mirror-edges*
    set-mirror-region*
    set-sheet-mirror-edges*
    shadow-pane
    sheet-actual-native-edges*
    sheet-cached-device-region
    sheet-cached-device-transformation
    sheet-cursor
    sheet-grabbed-pointer-cursor
    sheet-shell
    sheet-top-level-mirror
    sheet-top-level-sheet
    sheet-with-resources-mixin
    slider-decimal-places
    space-requirement+
    space-requirement+*
    space-requirement-cache-mixin
    space-requirement-combine
    space-requirement-components
    space-requirement-mixin
    standard-sheet
    standard-sheet-input-mixin
    standardize-text-style
    standardize-text-style-1
    stream-scan-character-for-writing
    stream-scan-string-for-writing
    stream-scan-string-for-writing-1
    string-height
    string-width
    text-field-echo-character
    text-style-index
    text-style-mapping*
    text-style-scale
    transform-distances
    transform-position-sequence
    transform-positions
    update-frame-settings
    update-mirror-region
    update-mirror-region-1
    update-mirror-transformation
    update-mirror-transformation-1
    update-region
    update-scroll-bars
    update-scroll-bar-value
    update-slider-value
    value-changed-gadget-event
    viewport-contents-extent
    viewport-region-changed
    window-shift-visible-region
    with-medium-clipping-region
    with-menu-as-popup
    with-mouse-grabbed-in-window
    wrapping-space-mixin))

#+allegro
(excl:ics-target-case
(:+ics

(defpackage clim-silica
  (:use)

  #+allegro
  (:import-from :excl #:non-dynamic-extent)
  (:export
   *kanji-servers*
   find-kanji-server-type))

)) ;; ics-target-case

(defpackage clim-internals
  (:use        :clim-lisp :clim-sys :clim :clim-utils :clim-silica)
  #+allegro (:implementation-packages :clim-internals :xt-silica)
  #+allegro
  (:import-from :excl #:non-dynamic-extent))



;; A package for casual use...
(defpackage clim-user
  (:use clim-lisp clim))

#+allegro
(flet ((lock-package (package)
	 (setq package (find-package package))
	 (setf (package-definition-lock package) t)))
  (mapcar #'lock-package '(
			   ;;-- We gotta fix the make-pane problem
			   ;;-- first
			   ;; clim
			   clim-utils
			   clim-silica
			   clim-internals
			   clim-lisp)))

(in-package :clim)

(cl:defparameter *clim-version* "2.3.14")

#+(version>= 5 0)
(cl:locally (cl:declare (cl:special excl::*version-info*))
  (cl:when (cl:boundp 'excl::*version-info*)
    (cl:push (cl:cons "CLIM" *clim-version*) excl::*version-info*)))

#+(version>= 6 0 pre-final 0)
(excl::lb1215005) ;; license check
