;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Package: CL-USER; Base: 10; Lowercase: Yes -*-

;; $fiHeader: packages.lisp,v 1.8 91/04/09 14:40:20 cer Exp $

(in-package #-ANSI-90 :user #+ANSI-90 :common-lisp-user)

"Copyright (c) 1991 Symbolics, Inc.  All rights reserved."

;; Define the CLIM-LISP package, a package designed to mimic ANSI Common Lisp
;; as closely as possible (including CLOS).
(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-LISP

 (:use #-ANSI-90 LISP #+ANSI-90 COMMON-LISP
       #+Allegro CLOS
       #+(and CLIM-uses-lisp-stream-classes Allegro) STREAM)
 
 #-ANSI-90
 (:shadowing-import-from #+PCL PCL
			 #+(and (not PCL) (or Genera Cloe-Runtime)) CLOS-INTERNALS
			 #+(and (not PCL) (not (or Genera Cloe-Runtime))) CLOS
   defstruct
   documentation
   setf)

 #-ANSI-90
 (:import-from #+PCL PCL #-PCL CLOS
   add-method
   allocate-instance
   built-in-class
   call-method
   call-next-method
   change-class
   class
   class-direct-subclasses
   class-direct-superclasses
   class-name
   class-of
   class-precedence-list
   class-prototype
   #+PCL classp
   compute-applicable-methods
   defclass
   defgeneric
   define-method-combination
   defmethod
   ensure-generic-function
   find-class
   find-method
   funcallable-standard-class
   function-keywords
   generic-flet
   generic-function
   generic-labels
   initialize-instance
   invalid-method-error
   make-instance
   make-instances-obsolete
   make-load-form
   make-method
   method
   method-combination
   method-combination-error
   method-qualifiers
   next-method-p
   no-applicable-method
   no-next-method
   print-object
   reinitialize-instance
   remove-method
   shared-initialize
   slot-boundp
   slot-exists-p
   slot-makunbound
   slot-missing
   slot-unbound
   slot-value
   standard
   standard-class
   standard-generic-function
   standard-method
   standard-object
   structure-class
   structure-object
   symbol-macrolet
   update-instance-for-different-class
   update-instance-for-redefined-class
   with-accessors
   with-slots)

 #+(and ANSI-90 (not CCL-2))
 (:import-from #+PCL PCL #-PCL CLOS
   class-direct-subclasses 
   class-direct-superclasses 
   class-precedence-list 
   class-prototype
   funcallable-standard-class)

 #+CCL-2
 (:import-from CCL
   class-direct-subclasses
   class-direct-superclasses
   class-precedence-list
   class-prototype
   class)

 #-ANSI-90
 (:shadowing-import-from #+Lucid LUCID-COMMON-LISP 
			 #+Allegro COMMON-LISP
			 #-(or Lucid Allegro) CONDITIONS
   *break-on-signals*
   *debugger-hook*
   abort
   arithmetic-error-operands
   arithmetic-error-operation
   arithmetic-error
   assert
   break
   ccase
   cell-error
   cell-error-name
   cerror
   check-type
   compute-restarts
   condition
   continue
   control-error
   ctypecase
   #-Lucid define-condition
   division-by-zero
   ecase
   end-of-file
   error
   etypecase
   file-error-pathname
   file-error
   find-restart
   floating-point-inexact
   floating-point-invalid-operation
   floating-point-overflow
   floating-point-underflow
   handler-bind
   handler-case
   ignore-errors
   invoke-debugger
   invoke-restart-interactively
   invoke-restart
   make-condition
   muffle-warning
   package-error-package
   package-error
   parse-error
   print-not-readable-object
   print-not-readable
   program-error
   restart-bind
   restart-case
   restart-name
   restart
   serious-condition
   signal
   simple-condition-format-arguments
   #-ANSI-90 simple-condition-format-string
   #+ANSI-90 simple-condition-format-control
   simple-condition
   simple-error
   simple-type-error
   simple-warning
   storage-condition
   store-value
   stream-error-stream
   stream-error
   style-warning
   type-error-datum
   type-error-expected-type
   type-error
   unbound-slot-instance
   unbound-slot
   unbound-variable
   undefined-function
   use-value
   warning
   warn
   with-simple-restart)

 #+Lucid (:shadow define-condition)

 #+(and Genera (not ANSI-90))
 (:import-from FUTURE-COMMON-LISP
   declaim
   define-compiler-macro
   defpackage
   dynamic-extent
   print-unreadable-object
   *print-readably*
   *read-eval*
   real
   with-standard-io-syntax)

 #+Symbolics
 (:import-from CLOS-INTERNALS
   compile-file-environment-p)

 #+Cloe-Runtime
 (:import-from CLOE
   with-standard-io-syntax)

 #+Lucid
 (:import-from LUCID-COMMON-LISP
   dynamic-extent)

 #+Allegro
 (:import-from EXCL
   dynamic-extent)

 #+Cloe-Runtime
 (:import-from SYSTEM
  stream-read-char
  stream-unread-char
  stream-read-char-no-hang
  stream-peek-char
  stream-listen
  stream-read-line
  stream-clear-input

  stream-write-char
  stream-line-column
  stream-start-line-p
  stream-write-string
  stream-terpri
  stream-fresh-line
  stream-finish-output
  stream-force-output
  stream-clear-output
  stream-advance-to-column

  stream-read-byte
  stream-write-byte
  )

 #+Minima
 (:import-from MINIMA-INTERNALS
  stream-read-char
  stream-unread-char
  stream-read-char-no-hang
  stream-peek-char
  stream-listen
  stream-read-line
  stream-clear-input

  stream-write-char
  stream-line-column
  stream-start-line-p
  stream-write-string
  stream-terpri
  stream-fresh-line
  stream-finish-output
  stream-force-output
  stream-clear-output
  stream-advance-to-column

  stream-read-byte
  stream-write-byte
  )

 ;; Stream Proposal -- Classes and class predicates.
 #-CLIM-uses-Lisp-stream-classes
 (:shadow
   ;; Class names
   fundamental-stream
   fundamental-input-stream
   fundamental-output-stream
   fundamental-character-stream
   fundamental-binary-stream
   fundamental-character-input-stream
   fundamental-character-output-stream
   fundamental-binary-input-stream
   fundamental-binary-output-stream

   ;; Function names
   input-stream-p
   output-stream-p
   open-stream-p
   streamp)

 #-CLIM-uses-Lisp-stream-functions
 (:shadow
   ;; CL stream input functions
   read-byte
   read-char
   unread-char
   read-char-no-hang
   peek-char
   listen
   read-line
   clear-input
   ;; CL stream output functions
   write-byte
   write-char
   write-string
   terpri
   fresh-line
   force-output
   finish-output
   clear-output
   format
   ;; Miscellaneous CL stream functions and macros
   stream-element-type
   close
   with-open-stream
   pathname 
   truename)

 ;; Import these symbols so that we can define methods for them.
 #+CCL-2
 (:import-from CCL
  stream-force-output
  stream-clear-input
  stream-fresh-line
  stream-listen)

 #+Genera
 (:shadow stream-element-type close with-open-stream pathname truename)

 #+Allegro
 (:shadow close with-open-stream pathname truename)

 (:export   
   ;; ANSI Common Lisp
   *print-readably*
   *read-eval*
   define-compiler-macro
   defpackage
   dynamic-extent
   print-unreadable-object
   real
   with-standard-io-syntax

   ;; Condition system
   *break-on-signals*
   *debugger-hook*
   abort
   arithmetic-error-operands
   arithmetic-error-operation
   arithmetic-error
   cell-error-name
   cell-error
   compute-restarts
   condition
   continue
   control-error
   define-condition
   division-by-zero
   end-of-file
   file-error-pathname
   file-error
   find-restart
   floating-point-inexact
   floating-point-invalid-operation
   floating-point-overflow
   floating-point-underflow
   handler-bind
   handler-case
   ignore-errors
   invoke-debugger
   invoke-restart-interactively
   invoke-restart
   make-condition
   muffle-warning
   package-error-package
   package-error
   parse-error
   print-not-readable-object
   print-not-readable
   program-error
   restart-bind
   restart-case
   restart-name
   restart
   serious-condition
   signal
   simple-condition-format-arguments
   #-ANSI-90 simple-condition-format-string
   #+ANSI-90 simple-condition-format-control
   simple-condition
   simple-error
   simple-type-error
   simple-warning
   storage-condition
   store-value
   stream-error-stream
   stream-error
   style-warning
   type-error-datum
   type-error-expected-type
   type-error
   unbound-slot-instance
   unbound-slot
   unbound-variable
   undefined-function
   use-value
   warning
   with-simple-restart

   ;; Stream Proposal
   fundamental-stream
   fundamental-input-stream
   fundamental-output-stream
   fundamental-character-stream
   fundamental-binary-stream
   fundamental-character-input-stream
   fundamental-character-output-stream
   fundamental-binary-input-stream
   fundamental-binary-output-stream

   stream-read-char
   stream-unread-char
   stream-read-char-no-hang
   stream-peek-char
   stream-listen
   stream-read-line
   stream-clear-input

   stream-write-char
   stream-line-column
   stream-start-line-p
   stream-write-string
   stream-terpri
   stream-fresh-line
   stream-finish-output
   stream-force-output
   stream-clear-output
   stream-advance-to-column

   stream-read-byte
   stream-write-byte
   
   ;; CLOS
   ;; Symbols from chapter 2
   add-method
   allocate-instance
   built-in-class
   call-method
   call-next-method
   change-class
   class
   class-name
   class-of
   compute-applicable-methods
   defclass
   defgeneric
   define-method-combination
   defmethod
   documentation
   ensure-generic-function
   find-class
   find-method
   function-keywords
   generic-flet
   generic-function
   generic-labels
   initialize-instance
   invalid-method-error
   make-instance
   make-instances-obsolete
   make-method
   method-combination-error
   method-qualifiers
   next-method-p
   no-applicable-method
   no-next-method
   print-object
   reinitialize-instance
   remove-method
   shared-initialize
   slot-boundp
   slot-exists-p
   slot-makunbound
   slot-missing
   slot-unbound
   slot-value
   standard-class
   standard-generic-function
   symbol-macrolet
   update-instance-for-different-class
   update-instance-for-redefined-class
   with-accessors
   with-slots
   ;; Post-88-002R additions that would have been in chapter 2
   describe-object
   make-load-form
   make-load-form-saving-slots
   ;; Not in Hornig's Chapter 2 list (?) but in both PCL and Genera CLOS, and
   ;; used by Silica
   class-direct-subclasses
   class-direct-superclasses
   class-precedence-list
   class-prototype
   funcallable-standard-class
   ;; Somehow missing from the above
   standard-object
   compile-file-environment-p

   ;; CLtL
   &allow-other-keys
   &aux
   &body
   &environment
   &key
   &optional
   &rest
   &whole
   *
   **
   ***
   *debug-io*
   *default-pathname-defaults*
   *error-output*
   *features*
   *load-verbose*
   *macroexpand-hook*
   *package*
   *print-array*
   *print-base*
   *print-case*
   *print-circle*
   *print-escape*
   *print-gensym*
   *print-length*
   *print-level*
   *print-pretty*
   *print-radix*
   *query-io*
   *random-state*
   *read-base*
   *read-default-float-format*
   *read-suppress*
   *readtable*
   *standard-input*
   *standard-output*
   *terminal-io*
   *trace-output*
   +
   ++
   +++
   -
   //
   ///
   /=
   /
   1+
   1-
   <
   <=
   =
   >
   >=
   abs
   acons
   acos
   acosh
   adjoin
   adjust-array
   adjustable-array-p
   alpha-char-p
   alphanumericp
   and
   append
   apply
   apropos
   apropos-list
   aref
   array-dimension
   array-dimension-limit
   array-dimensions
   array-element-type
   array-has-fill-pointer-p
   array-in-bounds-p
   array-rank-limit
   array-rank
   array-row-major-index
   array-total-size-limit
   array-total-size
   arrayp
   array
   ash 
   asin
   asinh
   assert
   assoc-if
   assoc-if-not
   assoc
   atanh
   atan
   atom
   bignum
   bit-and bit-ior bit-xor bit-eqv bit-nand bit-nor
   bit-andc1 bit-andc2 bit-orc1 bit-orc2 bit-not
   bit-vector-p
   bit-vector
   bit
   block
   boole-clr boole-set boole-1 boole-2 boole-c1 boole-c2 boole-and boole-ior
   boole-xor boole-eqv boole-nand boole-nor boole-andc1 boole-andc2 boole-orc1 boole-orc2
   boole
   both-case-p
   boundp
   break
   butlast
   byte
   byte-position
   byte-size
   caaaar
   caaadr
   caaar
   caadar
   caaddr
   caadr
   caar
   cadaar
   cadadr
   cadar
   caddar
   cadddr
   caddr
   cadr
   call-arguments-limit
   car
   case
   catch
   ccase
   cdaaar
   cdaadr
   cdaar
   cdadar
   cdaddr
   cdadr
   cdar
   cddaar
   cddadr
   cddar
   cdddar
   cddddr
   cdddr
   cddr
   cdr
   ceiling
   cerror
   char-code
   char-code-limit
   char-downcase
   char-equal
   char-greaterp
   char-int
   char-lessp
   char-name
   char-not-equal
   char-not-greaterp
   char-not-lessp
   char-upcase
   char/=
   char<
   char<=
   char=
   char>
   char>=
   character
   characterp
   char
   check-type
   cis
   clear-input
   clear-output
   close
   clrhash
   code-char
   coerce
   compilation-speed
   compile
   compile-file
   compiled-function-p
   compiled-function
   complex
   complexp
   concatenate
   cond
   conjugate
   cons
   consp
   constantp
   copy-alist
   copy-list
   copy-readtable
   copy-seq
   copy-symbol
   copy-tree
   cos
   cosh
   count
   count-if
   count-if-not
   ctypecase
   decf
   declaim
   declaration
   declare
   decode-float
   decode-universal-time
   defconstant
   define-modify-macro
   define-setf-method
   defmacro
   defparameter
   defsetf
   defstruct
   deftype
   defun
   defvar
   delete-duplicates
   delete-file
   delete-if
   delete-if-not
   delete
   denominator
   deposit-field
   describe
   digit-char
   digit-char-p
   directory-namestring
   directory
   disassemble
   do
   do*
   do-all-symbols
   do-external-symbols
   do-symbols
   documentation
   dolist
   dotimes
   double-float-epsilon
   double-float-negative-epsilon
   double-float
   dpb
   dribble
   ecase
   ed
   eighth 
   elt
   encode-universal-time
   endp
   enough-namestring
   eq
   eql
   equalp
   equal
   error
   etypecase
   eval
   eval-when
   evenp
   every
   exp
   export
   expt
   fboundp
   fceiling
   ffloor
   fifth
   file-author
   file-length
   file-namestring
   file-position
   file-write-date
   fill
   fill-pointer
   find
   find-all-symbols
   find-if
   find-if-not
   find-package
   find-symbol
   finish-output
   first
   fixnum
   flet
   float-digits
   float-precision
   float-radix
   float-sign
   floatp
   float
   floor
   fmakunbound
   force-output
   format
   fourth
   fresh-line
   fround
   ftruncate
   ftype
   funcall
   function
   functionp
   gcd
   gensym
   gentemp
   get-decoded-time 
   get-dispatch-macro-character
   get-internal-real-time
   get-internal-run-time
   get-macro-character
   get-output-stream-string
   get-properties
   get-setf-method
   get-setf-method-multiple-value
   get-universal-time
   getf
   gethash
   get
   go
   graphic-char-p
   hash-table-count
   hash-table-p
   hash-table
   host-namestring
   identity
   if
   ignore
   imagpart
   import
   in-package
   incf
   inline
   input-stream-p
   inspect
   integer-decode-float
   integer-length
   integerp
   integer
   internal-time-units-per-second
   intern
   intersection
   isqrt
   keywordp
   keyword
   labels
   lambda
   lambda-list-keywords
   lambda-parameters-limit
   last
   lcm
   ldb
   ldb-test
   ldiff
   least-negative-double-float
   least-negative-long-float
   least-negative-short-float
   least-negative-single-float
   least-positive-double-float
   least-positive-long-float
   least-positive-short-float
   least-positive-single-float
   length
   let
   let*
   lisp-implementation-type
   lisp-implementation-version
   list
   list*
   list-all-packages
   list-length
   listen
   listp
   load
   locally
   logandc1
   logandc2
   logand
   logbitp
   logcount
   logeqv
   logior
   lognand
   lognor
   lognot
   logorc1
   logorc2
   logtest
   logxor
   log
   long-float-epsilon
   long-float-negative-epsilon
   long-float
   long-site-name
   loop
   lower-case-p
   machine-instance
   machine-type
   machine-version
   macro-function
   macroexpand-1
   macroexpand
   macrolet
   make-array
   make-broadcast-stream
   make-concatenated-stream
   make-dispatch-macro-character
   make-echo-stream
   make-hash-table
   make-list
   make-package
   make-pathname
   make-random-state
   make-sequence
   make-string
   make-string-input-stream
   make-string-output-stream
   make-symbol
   make-synonym-stream
   make-two-way-stream
   makunbound
   mapc
   mapcan
   mapcar
   mapcon
   maphash
   maplist
   mapl
   map
   mask-field
   max
   member-if
   member-if-not
   member
   merge
   merge-pathnames
   min
   minusp
   mismatch
   mod
   most-negative-double-float
   most-negative-fixnum
   most-negative-long-float
   most-negative-short-float
   most-negative-single-float
   most-positive-double-float
   most-positive-fixnum
   most-positive-long-float
   most-positive-short-float
   most-positive-single-float
   multiple-value-bind
   multiple-value-call
   multiple-value-list
   multiple-value-prog1
   multiple-value-setq
   multiple-values-limit
   name-char
   namestring
   nbutlast
   nconc
   nil
   nintersection
   ninth
   not
   notany
   notevery
   notinline
   nreconc
   nreverse
   nset-difference
   nset-exclusive-or
   nstring-capitalize
   nstring-downcase
   nstring-upcase
   nsublis
   nsubst-if
   nsubst-if-not
   nsubstitute
   nsubstitute-if
   nsubstitute-if-not
   nsubst
   nth
   nthcdr
   null
   numberp
   number
   numerator
   nunion
   oddp
   open
   optimize
   or
   otherwise
   output-stream-p
   package-name
   package-nicknames
   package-shadowing-symbols
   package-use-list
   package-used-by-list
   packagep
   package
   pairlis
   parse-integer
   parse-namestring
   pathname-device
   pathname-directory
   pathname-host
   pathname-name
   pathname-type
   pathname-version
   pathnamep
   pathname
   peek-char
   phase
   pi
   plusp
   pop
   position
   position-if
   position-if-not
   pprint
   prin1-to-string
   prin1
   princ-to-string
   princ
   print
   probe-file
   proclaim
   prog
   prog*
   prog1
   prog2
   progn
   progv
   provide
   psetf
   psetq
   push
   pushnew
   quote
   random
   random-state-p
   random-state
   rassoc-if
   rassoc-if-not
   rassoc
   rationalize
   rationalp
   rational
   ratio
   read-byte
   read-char
   read-char-no-hang
   read-delimited-list
   read-from-string
   read-line
   read-preserving-whitespace
   readtablep
   readtable
   read
   realpart
   reduce
   remf
   remhash
   remove-duplicates
   remove-if 
   remove-if-not
   remove
   remprop
   rem
   rename-file
   rename-package
   replace
   require
   rest
   return-from
   return
   revappend
   reverse
   room
   rotatef
   round
   rplaca
   rplacd
   safety
   satisfies
   sbit
   scale-float
   schar
   search
   second 
   sequence
   set
   set-difference
   set-dispatch-macro-character
   set-exclusive-or
   set-macro-character
   set-syntax-from-char
   setf
   setq
   seventh
   shadow
   shadowing-import
   shiftf
   short-float-epsilon
   short-float-negative-epsilon
   short-float
   short-site-name
   signed-byte
   signum
   simple-array
   simple-bit-vector-p
   simple-bit-vector
   simple-string-p
   simple-string
   simple-vector-p
   simple-vector
   sin
   single-float-epsilon
   single-float-negative-epsilon
   single-float
   sinh
   sixth
   sleep
   software-type
   software-version
   some
   sort
   space
   special-form-p
   special
   speed
   sqrt
   stable-sort
   standard-char-p
   standard-char
   step
   stream-element-type
   streamp
   stream
   string
   string-capitalize
   string-downcase
   string-equal
   string-greaterp
   string-left-trim
   string-lessp
   string-not-equal
   string-not-greaterp
   string-not-lessp
   string-right-trim
   string-trim
   string-upcase
   string/=
   string<
   string<=
   string=
   string>
   string>=
   stringp
   structure
   sublis
   subseq
   subsetp
   subst-if
   subst-if-not
   substitute
   substitute-if
   substitute-if-not
   subst
   subtypep
   svref
   sxhash
   symbol-function
   symbol-name
   symbol-package
   symbol-plist
   symbol-value
   symbolp
   symbol
   t
   tagbody
   tailp
   tan
   tanh
   tenth
   terpri
   the
   third
   throw
   time
   trace
   tree-equal
   truename
   truncate
   type-of
   typecase
   typep
   type
   unexport
   unintern
   union
   unless
   unread-char
   unsigned-byte
   untrace
   unuse-package
   unwind-protect
   upper-case-p
   use-package
   user-homedir-pathname
   values
   values-list
   variable
   vector
   vector-pop
   vector-push-extend
   vector-push
   vectorp
   warn
   when
   with-input-from-string
   with-open-file
   with-open-stream
   with-output-to-string
   write
   write-byte
   write-char
   write-line
   write-string
   write-to-string
   y-or-n-p
   yes-or-no-p
   zerop)

 #+Genera
 (:import-from FUTURE-COMMON-LISP
   base-string
   broadcast-stream
   broadcast-stream-streams
   *compile-file-pathname*
   compile-file-pathname
   *compile-print*
   compiler-macro-function
   *compile-verbose*
   concatenated-stream
   concatenated-stream-streams
   copy-pprint-dispatch
   debug
   destructuring-bind
   echo-stream
   echo-stream-input-stream
   echo-stream-output-stream
   ;ENCAPSULATED
   fdefinition
   file-stream
   file-string-length
   formatter
   *gensym-counter*
   load-logical-pathname-translations
   *load-pathname*
   *load-print*
   load-time-value
   *load-truename*
   logical-pathname
   logical-pathname-translations
   loop-finish 
   nth-value
   pathname-match-p
   pprint-dispatch
   pprint-exit-if-list-exhausted
   pprint-fill
   pprint-indent
   pprint-linear
   pprint-logical-block
   pprint-newline
   pprint-pop
   pprint-tab
   pprint-tabular
   *print-lines*
   *print-miser-width*
   *print-pprint-dispatch*
   *print-right-margin*
   readtable-case
   row-major-aref
   set-pprint-dispatch
   ;SIMPLE-ARRAY-BASE-CHARACTER
   simple-base-string
   stream-external-format
   string-stream
   synonym-stream
   synonym-stream-symbol
   translate-logical-pathname
   translate-pathname
   two-way-stream
   two-way-stream-input-stream
   two-way-stream-output-stream
   upgraded-array-element-type
   upgraded-complex-part-type
   wild-pathname-p
   with-compilation-unit
   with-condition-restarts
   with-hash-table-iterator
   with-package-iterator)

 ;; more ANSI exports.  Why were these not exported?
 (:export 
   ;; why not exported here?
   open-stream-p
   ;; not supported in Genera yet, but not used by clim either!
   ;with-added-methods
   structure-class
   standard-method 
   method-combination
   method
   #+PCL classp
   augment-environment
   base-string
   broadcast-stream
   broadcast-stream-streams
   *compile-file-pathname*
   compile-file-pathname
   *compile-print*
   compiler-macroexpand
   compiler-macroexpand-1
   compiler-macro-function
   *compile-verbose*
   concatenated-stream
   concatenated-stream-streams
   copy-pprint-dispatch
   debug
   destructuring-bind
   echo-stream
   echo-stream-input-stream
   echo-stream-output-stream
   ;encapsulated
   fdefinition
   file-stream
   file-string-length
   formatter
   *gensym-counter*
   load-logical-pathname-translations
   *load-pathname*
   *load-print*
   load-time-value
   *load-truename*
   logical-pathname
   logical-pathname-translations
   loop-finish 
   nth-value
   pathname-match-p
   pprint-dispatch
   pprint-exit-if-list-exhausted
   pprint-fill
   pprint-indent
   pprint-linear
   pprint-logical-block
   pprint-newline
   pprint-pop
   pprint-tab
   pprint-tabular
   *print-lines*
   *print-miser-width*
   *print-pprint-dispatch*
   *print-right-margin*
   readtable-case
   row-major-aref
   set-pprint-dispatch
   simple-array-base-character
   simple-base-string
   stream-external-format
   string-stream
   synonym-stream
   synonym-stream-symbol
   translate-logical-pathname
   translate-pathname
   two-way-stream
   two-way-stream-input-stream
   two-way-stream-output-stream
   upgraded-array-element-type
   upgraded-complex-part-type
   wild-pathname-p
   with-compilation-unit
   with-condition-restarts
   with-hash-table-iterator
   with-package-iterator))

;; Get around a CCL-2 bug with DEFPACKAGE
#+CCL-2
(eval-when (eval compile load)
  (export '(()) "CLIM-LISP"))

#+(and Genera lock-CLIM-packages) (setf (si:pkg-locked (find-package "CLIM-LISP")) t)

#+Genera (pushnew (find-package "CLIM-LISP") si:*reasonable-packages*)


;; Define the CLIM-SYS package
(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-SYS
  (:use)				;use nothing
  (:export
    ;; CLIM-SYS
    all-processes
    allocate-resource
    clear-resource
    current-process
    deallocate-resource
    defresource
    destroy-process
    make-lock
    make-process
    make-recursive-lock
    process-interrupt
    process-wait
    process-wait-with-timeout
    process-yield
    using-resource
    with-lock-held
    with-recursive-lock-held
    without-scheduling))

#+(and Genera lock-CLIM-packages) (setf (si:pkg-locked (find-package "CLIM-SYS")) t)


;; Define the CLIM package
(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM
  (:use)				;use nothing
  (:import-from CLIM-LISP
    and
    character
    close
    complex
    float
    integer
    keyword
    member
    nil
    null
    number
    or
    pathname 
    ratio
    rational
    real 
    sequence
    stream-advance-to-column
    stream-clear-input
    stream-clear-output
    stream-element-type
    stream-finish-output
    stream-force-output
    stream-fresh-line
    stream-line-column
    stream-listen
    stream-peek-char
    stream-read-byte
    stream-read-char
    stream-read-char-no-hang
    stream-read-line
    stream-start-line-p
    stream-terpri
    stream-unread-char
    stream-write-byte
    stream-write-char
    stream-write-string
    string
    symbol
    t
    truename
    with-open-stream)

  (:export
    ;; Geometry
    +everywhere+
    +nowhere+
    area
    areap
    ellipse
    ellipse-center-point
    ellipse-center-point*
    ellipse-end-angle
    ellipse-radii
    ellipse-start-angle
    ellipsep
    elliptical-arc
    elliptical-arc-p
    line
    line-end-point
    line-end-point*
    line-start-point
    line-start-point*
    linep
    make-ellipse
    make-ellipse*
    make-elliptical-arc
    make-elliptical-arc*
    make-line
    make-line*
    make-point
    make-polygon
    make-polygon*
    make-polyline
    make-polyline*
    make-rectangle
    make-rectangle*
    map-over-polygon-coordinates
    map-over-polygon-segments
    map-over-region-set-regions
    path
    pathp
    point
    point-position*
    point-x
    point-y
    pointp
    polygon
    polygon-points
    polygonp
    polyline
    polyline-closed
    polylinep
    rectangle
    rectangle-edges*
    rectangle-height
    rectangle-max-point
    rectangle-max-x
    rectangle-max-y
    rectangle-min-point
    rectangle-min-x
    rectangle-min-y
    rectangle-size
    rectangle-width
    rectanglep
    region
    region-contains-point*-p
    region-contains-region-p
    region-difference
    region-equal
    region-intersection
    region-intersects-region-p
    region-set
    region-set-p
    region-set-regions
    region-union
    regionp
    standard-ellipse
    standard-elliptical-arc
    standard-line
    standard-point
    standard-polygon
    standard-polyline
    standard-rectangle
    standard-region-difference
    standard-region-intersection
    standard-region-union

    ;; Bounding rectangles
    bounding-rectangle
    bounding-rectangle*
    bounding-rectangle-height
    bounding-rectangle-max-x
    bounding-rectangle-max-y
    bounding-rectangle-min-x
    bounding-rectangle-min-y
    bounding-rectangle-p
    bounding-rectangle-position*
    bounding-rectangle-size
    bounding-rectangle-width
    bounding-rectangle-left
    bounding-rectangle-top
    bounding-rectangle-right
    bounding-rectangle-bottom
    make-bounding-rectangle
    standard-bounding-rectangle
    with-bounding-rectangle*
    
    ;; Transformations
    +identity-transformation+
    compose-rotation-with-transformation
    compose-scaling-with-transformation
    compose-transformation-with-rotation
    compose-transformation-with-scaling
    compose-transformation-with-translation
    compose-transformations
    compose-translation-with-transformation
    even-scaling-transformation-p
    identity-transformation-p
    invert-transformation
    invertible-transformation-p
    make-3-point-transformation
    make-3-point-transformation*
    make-reflection-transformation
    make-reflection-transformation*
    make-rotation-transformation
    make-rotation-transformation*
    make-scaling-transformation
    make-scaling-transformation*
    make-transformation
    make-translation-transformation
    rectilinear-transformation-p
    reflection-transformation-p
    reflection-underspecified
    rigid-transformation-p
    scaling-transformation-p
    singular-transformation
    transform-distance
    transform-point*
    transform-rectangle*
    transform-region
    transformation
    transformation-equal
    transformation-error
    transformation-underspecified
    transformationp
    translation-transformation-p
    untransform-distance
    untransform-point*
    untransform-rectangle*
    untransform-region
    
    ;; Windowing substrate
    *default-server-path*
    +control-key+
    +hyper-key+
    +meta-key+
    +pointer-left-button+
    +pointer-middle-button+
    +pointer-right-button+
    +shift-key+
    +super-key+
    add-watcher
    bursting-input-queuer
    bury-sheet
    child-containing-point
    child-containing-point*
    children-overlapping-rectangle*
    children-overlapping-region
    define-sheet-class
    delegate-sheet-delegate
    delegate-sheet-input-mixin
    delete-watcher
    destroy-port
    device-clipping-region
    device-event
    device-transformation
    disable-mirror
    dispatch-crossing-event
    dispatch-device-event
    dispatch-event
    dispatch-repaint
    display-medium
    distribute-device-event
    distribute-event
    enable-mirror
    enter-region
    event
    event-listen
    event-modifier-state
    event-peek
    event-read
    event-read-no-hang
    event-sheet
    event-timestamp
    event-type
    event-unread
    eventp
    exit-region
    fetch-clipping-region
    find-graft
    find-port
    graft-height
    graft-orientation
    graft-pixels-per-inch
    graft-pixels-per-millimeter
    graft-units
    graft-width
    handle-event
    handle-repaint
    immediate-repainting-mixin
    immediate-sheet-input-mixin
    invalidate-cached-regions
    invalidate-cached-transformations
    invoking-input-contract
    key-modifier-state-match-p
    key-press-event
    key-release-event
    keyboard-event
    keyboard-event-character
    keyboard-event-key-name
    make-sheet
    make-standard-sheet
    map-over-grafts
    map-over-ports
    map-sheet-bounding-rectangle*-to-child
    map-sheet-bounding-rectangle*-to-parent
    map-sheet-point*-to-child
    map-sheet-point*-to-parent
    medium
    medium-background
    medium-clipping-region
    medium-default-text-style
    medium-foreground
    medium-ink
    medium-line-style
    medium-merged-text-style
    medium-text-style
    medium-transformation
    mediump
    mute-input-contract
    mute-repainting-mixin
    mute-sheet-input-mixin
    mute-sheet-output-mixin
    note-sheet-adopted
    note-sheet-degrafted
    note-sheet-disabled
    note-sheet-disowned
    note-sheet-enabled
    note-sheet-grafted
    note-sheet-region-changed
    note-sheet-transformation-changed
    permanent-medium-sheet-output-mixin
    pointer-button-event
    pointer-button-hold-event
    pointer-button-press-event
    pointer-button-release-event
    pointer-click-event
    pointer-click-hold-event
    pointer-double-click-event
    pointer-enter-event
    pointer-event
    pointer-event-button
    pointer-event-native-x
    pointer-event-native-y
    pointer-event-pointer
    pointer-event-x
    pointer-event-y
    pointer-exit-event
    pointer-motion-event
    poll-pointer
    port-keyboard-input-focus
    port-properties
    port-server-path
    primitive-sheet-output-mixin
    process-next-event
    queue-event
    queue-input
    queue-repaint
    raise-sheet
    realize-graft
    realize-mirror
    reorder-sheets
    repaint-sheet
    reset-watcher
    restart-port
    sheet
    sheet-adopt-child
    sheet-allocated-region
    sheet-ancestor-p
    sheet-children
    sheet-delta-transformation
    sheet-device-region
    sheet-device-transformation
    sheet-direct-mirror
    sheet-disown-child
    sheet-enabled-children
    sheet-enabled-p
    sheet-event-queue
    sheet-graft
    sheet-grafted-p
    sheet-identity-transformation-mixin
    sheet-leaf-mixin
    sheet-medium
    sheet-mirror
    sheet-mirrored-ancestor
    sheet-multiple-child-mixin
    sheet-native-region
    sheet-native-transformation
    sheet-occluding-sheets
    sheet-parent
    sheet-port
    sheet-region
    sheet-siblings
    sheet-single-child-mixin
    sheet-transformation
    sheet-transformation-mixin
    sheet-translation-mixin
    sheet-viewable-p
    sheet-y-inverting-transformation-mixin
    sheetp
    silica-clipping-region
    silica-medium-transformation
    standard-event-distributor
    standard-input-contract
    standard-repainting-mixin
    standard-sheet-input-mixin
    standard-sheet-output-mixin
    temporary-medium-sheet-output-mixin
    timer-event
    using-display-medium
    window-configuration-event
    window-event
    
    window-event-mirrored-sheet
    window-event-native-region
    window-event-region
    window-repaint-event
    with-graft-locked
    with-output-protection
    with-port-locked
    with-sheet-medium
    with-sheet-medium-bound
    
    ;; Drawing options
    contrasting-dash-pattern-limit
    invoke-with-drawing-options
    line-style
    line-style-cap-shape
    line-style-dashes
    line-style-joint-shape
    line-style-p
    line-style-thickness
    line-style-unit
    make-contrasting-dash-patterns
    make-line-style
    medium-background
    medium-clipping-region
    medium-current-text-style
    medium-default-text-style
    medium-foreground
    medium-ink
    medium-line-style
    medium-text-style
    medium-transformation
    standard-line-style
    with-drawing-options
    with-first-quadrant-coordinates
    with-local-coordinates
    with-rotation
    with-scaling
    with-translation
    
    ;; Text styles
    *default-text-style*
    invoke-with-text-style
    make-device-font-text-style
    make-text-style
    merge-text-styles
    parse-text-style
    standard-text-style
    text-size
    text-style
    text-style-ascent
    text-style-components
    text-style-descent
    text-style-face
    text-style-family
    text-style-fixed-width-p
    text-style-height
    text-style-mapping
    text-style-p
    text-style-size
    text-style-width
    with-text-face
    with-text-family
    with-text-size
    with-text-style
    
    ;; Graphics
    allocate-pixmap
    copy-area
    copy-from-pixmap
    copy-to-pixmap
    deallocate-pixmap
    draw-arrow
    draw-arrow*
    draw-circle
    draw-circle*
    draw-ellipse
    draw-ellipse*
    draw-line
    draw-line*
    draw-lines
    draw-lines*
    draw-oval
    draw-oval*
    draw-point
    draw-point*
    draw-points
    draw-points*
    draw-polygon
    draw-polygon*
    draw-rectangle*
    draw-text
    draw-text*
    medium-draw-ellipse*
    medium-draw-line*
    medium-draw-lines*
    medium-draw-point*
    medium-draw-points*
    medium-draw-polygon*
    medium-draw-rectangle*
    medium-draw-text*
    pixmap-height
    pixmap-width
    port-draw-character*
    port-draw-ellipse*
    port-draw-line*
    port-draw-lines*
    port-draw-point*
    port-draw-points*
    port-draw-polygon*
    port-draw-rectangle*
    port-draw-string*
    with-output-to-pixmap-stream
    
    ;; Color
    +background-ink+
    +flipping-ink+
    +foreground-ink+
    color
    color-ihs
    color-rgb
    colorp
    contrasting-inks-limit
    design
    designp
    make-contrasting-inks
    make-flipping-ink
    make-gray-color
    make-ihs-color
    make-opacity
    make-rgb-color
    opacity
    opacity-value
    opacityp
    
    ;; Patterns
    compose-in
    compose-out
    compose-over
    draw-design
    draw-pattern*
    make-pattern
    make-rectangular-tile
    make-stencil
    
    ;; Extended output
    beep
    cursor
    cursor-position*
    cursor-sheet
    cursor-visibility
    cursorp
    display-cursor
    extended-output-stream
    extended-output-stream-p
    sheet-buffering-output-p
    standard-extended-output-stream
    standard-output-stream
    standard-text-cursor
    stream-advance-to-column
    stream-baseline
    stream-character-width
    stream-clear-output
    stream-cursor-position*
    stream-end-of-line-action
    stream-end-of-page-action
    stream-finish-output
    stream-force-output
    stream-fresh-line
    stream-increment-cursor-position*
    stream-line-column
    stream-line-height
    stream-start-line-p
    stream-string-width
    stream-terpri
    stream-text-cursor
    stream-text-margin
    stream-vertical-spacing
    stream-write-char
    stream-write-string
    with-end-of-line-action
    with-end-of-page-action
    with-output-buffered
    with-room-for-graphics
    
    ;; Output recording
    add-character-output-to-text-record
    add-output-record
    add-string-output-to-text-record
    clear-output-record
    delete-output-record
    displayed-output-record
    displayed-output-record-p
    erase-output-record
    graphics-displayed-output-record
    graphics-displayed-output-record-p
    highlight-output-record
    invoke-with-new-output-record
    invoke-with-output-recording-options
    invoke-with-output-to-output-record
    make-design-from-output-record
    map-over-output-records-containing-point*
    map-over-output-records-overlapping-region
    output-record
    output-record-children
    output-record-count
    output-record-end-cursor-position*
    output-record-hit-detection-rectangle*
    output-record-p
    output-record-parent
    output-record-position*
    output-record-refined-sensitivity-test
    output-record-start-cursor-position*
    output-recording-stream
    output-recording-stream-p
    recompute-extent-for-changed-child
    recompute-extent-for-new-child
    replay
    replay-output-record
    standard-output-recording-stream
    standard-sequence-output-record
    standard-tree-output-history
    standard-tree-output-record
    stream-add-character-output
    stream-add-output-record
    stream-add-string-output
    stream-close-text-output-record
    stream-current-output-record
    stream-drawing-p
    stream-output-history
    stream-output-history-mixin
    stream-replay
    stream-recording-p
    stream-text-output-record
    text-displayed-output-record
    text-displayed-output-record-p
    text-displayed-output-record-string
    tree-recompute-extent
    with-new-output-record
    with-output-recording-options
    with-output-to-output-record
    
    ;; Table formatting
    adjust-item-list-cells
    adjust-multiple-columns
    adjust-table-cells
    cell-align-x
    cell-align-y
    cell-min-height
    cell-min-width
    cell-output-record
    cell-output-record-p
    column-output-record
    column-output-record-p
    format-items
    formatting-cell
    formatting-column
    formatting-item-list
    formatting-row
    formatting-table
    item-list-output-record
    item-list-output-record-p
    map-over-item-list-cells
    map-over-row-cells
    map-over-table-elements
    row-output-record
    row-output-record-p
    standard-cell-output-record
    standard-column-output-record
    standard-item-list-output-record
    standard-row-output-record
    standard-table-output-record
    table-output-record
    table-output-record-p
    
    ;; Graph formatting
    define-graph-type
    format-graph-from-root
    format-graph-from-roots
    generate-graph-nodes
    graph-node-children
    graph-node-object
    graph-node-output-record
    graph-node-output-record-p
    graph-node-parents
    graph-output-record
    graph-output-record-p
    graph-root-nodes
    layout-graph-edges
    layout-graph-nodes
    standard-graph-node-output-record
    standard-graph-output-record
    
    ;; Bordered output
    define-border-type
    surrounding-output-with-border
    
    ;; Text formatting
    filling-output
    format-textual-list
    indenting-output
    
    ;; Incremental redisplay
    augment-draw-set
    cache-output-record
    compute-differences
    decache-inferior-output-record
    find-cached-output-record
    find-inferior-output-record
    incremental-redisplay
    inferior-output-record-changed
    match-output-records
    new-output-records
    output-record-cache-value
    output-record-contents-ok
    output-record-displayer
    output-record-fixed-position
    output-record-unique-id
    propagate-inferior-output-record-changes-p
    propagate-output-record-changes
    recompute-contents-ok
    redisplay
    redisplay-output-record
    standard-updating-output-record
    redisplayable-stream-p
    updating-output
    updating-output-record
    updating-output-record-p
    
    ;; Extended input
    *input-wait-handler*
    *input-wait-test*
    *pointer-button-press-handler*
    add-gesture-name
    define-gesture-name
    delete-gesture-name
    drag-output-record
    dragging-output
    event-matches-gesture-name-p
    extended-input-stream
    extended-input-stream-p
    gesture-processing-handler
    modifier-state-matches-gesture-name-p
    pointer
    pointer-buttons
    pointer-cursor
    pointer-port
    pointer-position*
    pointer-sheet
    pointerp
    read-gesture
    standard-extended-input-stream
    standard-input-stream
    standard-pointer
    stream-clear-input
    stream-input-buffer
    stream-input-wait
    stream-listen
    stream-peek-char
    stream-pointer-position*
    stream-pointers
    stream-primary-pointer
    stream-read-char
    stream-read-char-no-hang
    stream-read-gesture
    stream-read-line
    stream-restore-input-focus
    stream-set-input-focus
    stream-unread-char
    stream-unread-gesture
    tracking-pointer
    unread-gesture
    with-input-focus
    
    ;; Presentation types
    *input-context*
    *null-presentation*
    +gadget-dialog-view+
    +gadget-menu-view+
    +gadget-view+
    +pointer-documentation-view+
    +textual-dialog-view+
    +textual-menu-view+
    +textual-view+
    accept
    accept-from-string
    accept-1
    accept-method
    accept-present-default
    accept-present-default-method
    and
    blank-area
    boolean
    call-presentation-generic-function
    call-presentation-menu
    call-presentation-translator
    character
    class-presentation-type-name
    completion
    complex
    default-describe-presentation-type
    define-click-and-drag-translator
    define-default-presentation-method
    define-presentation-action
    define-presentation-generic-function
    define-presentation-method
    define-presentation-to-command-translator
    define-presentation-translator
    define-presentation-type
    define-presentation-type-abbreviation
    describe-presentation-type
    describe-presentation-type-method
    document-presentation-translator
    expand-presentation-type-abbreviation
    expand-presentation-type-abbreviation-1
    expression
    find-applicable-translators
    find-innermost-applicable-presentation
    find-presentation-translators
    find-presentation-type-class
    float
    form
    frame-document-highlighted-presentation
    gadget-dialog-view
    gadget-menu-view
    gadget-view
    highlight-applicable-presentation
    highlight-presentation
    highlight-presentation-method
    integer
    keyword
    make-presentation-type-specifier
    map-over-presentation-type-supertypes
    map-over-presentation-type-supertypes-method
    member
    member-alist
    member-sequence
    nil
    null
    null-or-type
    number
    or
    pathname
    pointer-documentation-view
    port-dialog-view
    present
    present-method
    present-to-string
    presentation
    presentation-default-preprocessor
    presentation-default-preprocessor-method
    presentation-matches-context-type
    presentation-modifier
    presentation-object
    presentation-refined-position-test
    presentation-single-box
    presentation-subtypep
    presentation-subtypep-method
    presentation-type
    presentation-type-direct-supertypes
    presentation-type-history
    presentation-type-history-method
    presentation-type-of
    presentation-type-name
    presentation-type-options
    presentation-type-parameters
    presentation-type-specifier-p
    presentation-type-specifier-p-method
    presentation-typep
    presentation-typep-method
    presentationp
    prompt-for-accept
    prompt-for-accept-1
    ratio
    rational
    real
    sequence
    sequence-enumerated
    set-highlighted-presentation
    standard-presentation
    stream-accept
    stream-default-view
    stream-present
    string
    subset
    subset-alist
    subset-completion
    subset-sequence
    symbol
    t
    test-presentation-translator
    textual-dialog-view
    textual-menu-view
    textual-view
    throw-highlighted-presentation
    token-or-type
    type-or-string
    unhighlight-highlighted-presentation
    view
    viewp
    with-input-context
    with-output-as-presentation
    with-presentation-type-decoded
    with-presentation-type-options
    with-presentation-type-parameters
    
    ;; Input editing and completion
    *abort-gestures*
    *activation-gestures*
    *blip-gestures*
    *completion-gestures*
    *help-gestures*
    *possibilities-gestures*
    *standard-activation-gestures*
    abort-gesture
    activation-gesture-p
    blip-gesture-p
    complete-from-generator
    complete-from-possibilities
    complete-input
    completing-from-suggestions
    erase-input-buffer
    immediate-rescan
    input-editing-stream
    input-editing-stream-p
    input-editor-buffer
    input-not-of-required-type
    interactive-stream-p
    presentation-replace-input
    queue-rescan
    read-token
    redraw-input-buffer
    replace-input
    rescan-if-necessary
    reset-scan-pointer
    simple-parse-error
    standard-input-editing-stream
    stream-insertion-pointer
    stream-process-gesture
    stream-read-gesture
    stream-rescanning-p
    stream-scan-pointer
    stream-unread-gesture
    suggest
    with-accept-help
    with-activation-gestures
    with-blip-gestures
    with-input-editing
    with-input-editor-typeout
    write-token
    
    ;; Menus
    menu-choose
    menu-choose-from-drawer
    menu-item
    menu-item-display
    menu-item-options
    menu-item-value
    port-menu-choose
    print-menu-item
    with-menu
    
    ;; Dialogs
    accept-values
    accept-values-command-button
    accept-values-resynchronize
    accepting-values
    display-exit-boxes
    
    ;; Command processor
    *command-argument-delimiters*
    *command-dispatchers*
    *command-name-delimiters*
    *command-parser*
    *command-unparser*
    *numeric-argument-marker*
    *partial-command-parser*
    *unsupplied-argument-marker*
    add-command-to-command-table
    add-keystroke-to-command-table
    add-menu-item-to-command-table
    add-presentation-translator-to-command-table
    command
    command-accessible-in-command-table-p
    command-already-present
    command-arguments
    command-line-command-parser
    command-line-command-unparser
    command-line-name-for-command
    command-line-read-remaining-arguments-for-partial-command
    command-menu-item-options
    command-menu-item-type
    command-menu-item-value
    command-name
    command-not-accessible
    command-not-present
    command-or-form
    command-present-in-command-table-p
    command-table
    command-table-already-exists
    command-table-error
    command-table-inherit-from
    command-table-name
    command-table-not-found
    command-table-p
    define-command
    define-command-table
    display-command-table-menu
    do-command-table-inheritance
    find-command-from-command-line-name
    find-command-table
    find-keystroke-item
    find-menu-item
    find-presentation-translator
    global-command-table
    lookup-keystroke-command-item
    lookup-keystroke-item
    make-command-table
    map-over-command-table-commands
    map-over-command-table-keystrokes
    map-over-command-table-menu-items
    map-over-command-table-names
    map-over-command-table-translators
    menu-choose-command-from-command-table
    menu-command-parser
    menu-read-remaining-arguments-for-partial-command
    partial-command-p
    read-command
    read-command-using-keystrokes
    remove-command-from-command-table
    remove-keystroke-from-command-table
    remove-menu-item-from-command-table
    remove-presentation-translator-from-command-table
    standard-command-table
    substitute-numeric-argument-marker
    user-command-table
    with-command-table-keystrokes
    
    ;; Application frames
    *application-frame*
    *default-frame-manager*
    *pointer-documentation-output*
    adopt-frame
    application-frame
    application-frame-p
    application-pane
    client-setting
    command-enabled
    default-frame-top-level
    define-application-frame
    disable-frame
    disown-frame
    display-command-menu
    enable-frame
    execute-frame-command
    find-frame-manager
    find-pane-for-frame
    frame-click-and-drag-feedback
    frame-click-and-drag-highlighting
    frame-command-table
    frame-current-layout
    frame-current-panes
    frame-document-highlighted-presentation
    frame-error-output
    frame-exit
    frame-find-innermost-applicable-presentation
    frame-input-context-button-press-handler
    frame-maintain-presentation-histories
    frame-manager
    frame-name
    frame-named-panes
    frame-pane
    frame-pane-name
    frame-panes
    frame-pointer-documentation-output
    frame-pretty-name
    frame-properties
    frame-query-io
    frame-replay
    frame-standard-input
    frame-standard-output
    frame-state
    frame-top-level-sheet
    generate-panes
    get-frame-pane
    interactor-pane
    layout-frame
    layout-frame-panes
    make-application-frame
    note-command-disabled
    note-command-enabled
    note-frame-disabled
    note-frame-enabled
    notify-user
    pane-frame
    pane-needs-redisplay
    panes-need-redisplay
    read-frame-command
    reconfigure-frame
    redisplay-frame-command-menu
    redisplay-frame-pane
    redisplay-frame-panes
    reset-frame
    run-frame-top-level
    shrink-frame
    standard-application-frame
    window-clear
    window-erase-viewport
    window-refresh
    window-viewport
    window-viewport-position*
    with-application-frame
    with-frame-manager
    
    ;; Panes
    +fill+
    basic-clim-pane
    basic-stream-pane
    bboard-pane
    border-pane
    bordering
    change-space-requirement
    changing-space-requirements
    depressing
    extended-stream-pane
    grid-pane
    hbox-pane
    horizontal-divider
    horizontally
    hrack-pane
    label-button-pane
    label-pane
    labelled
    line-editor-pane
    list-pane
    making-application-pane
    one-of-pane
    outlined-pane
    pane-background
    pane-foreground
    radio-button-pane
    raising
    realize-pane
    realize-pane-1
    restraining
    restraining-pane
    scrollable-pane
    scrolling
    shadow-pane
    spacer-pane
    spacing
    table-pane
    tabling
    text-stream-pane
    vbox-pane
    vertical-divider
    vertically
    vrack-pane
    with-look-and-feel-realization
    
    ;; Adaptive toolkit
    activate-callback
    activate-gadget
    button-label
    button-text-style
    cascade-button-menu-group
    deactivate-gadget
    gadget-client
    gadget-id
    gadget-value
    menu-bar
    note-gadget-activated
    note-gadget-deactivated
    push-button
    push-button-show-as-default-p
    radio-box
    radio-box-current-selection
    scroll-bar
    scroll-bar-max-value
    scroll-bar-min-value
    scroll-bar-orientation
    scroll-bar-page-increment
    scroll-bar-unit-increment
    slider
    slider-max-value
    slider-min-value
    slider-orientation
    slider-show-value-p
    text-field
    toggle-button
    toggle-button-indicator-type
    value-changed-callback
    
    ;; Pane layout
    allocate-space
    compose-space
    make-space-requirement
    note-space-requirement-changed
    space-requirement-height
    space-requirement-max-height
    space-requirement-max-width
    space-requirement-min-height
    space-requirement-min-width
    space-requirement-width
    
    ;; Encapsulating streams
    *original-stream*
    encapsulating-stream
    encapsulating-stream-p
    encapsulating-stream-stream
    standard-encapsulating-stream)

  ;; Primary colors
  (:export
    +red+
    +green+
    +blue+
    +cyan+
    +magenta+
    +yellow+
    +black+
    +white+)
  
  ;; Stupid CLX color names
  (:export
    +alice-blue+
    +antique-white+
    +aquamarine+
    +azure+
    +beige+
    +bisque+
    +black+
    +blanched-almond+
    +blue-violet+
    +brown+
    +burlywood+
    +cadet-blue+
    +chartreuse+
    +chocolate+
    +coral+
    +cornflower-blue+
    +cornsilk+
    +dark-goldenrod+
    +dark-green+
    +dark-khaki+
    +dark-olive-green+
    +dark-orange+
    +dark-orchid+
    +dark-salmon+
    +dark-sea-green+
    +dark-slate-blue+
    +dark-slate-gray+
    +dark-turquoise+
    +dark-violet+
    +deep-pink+
    +deep-sky-blue+
    +dim-gray+
    +dodger-blue+
    +firebrick+
    +floral-white+
    +forest-green+
    +gainsboro+
    +ghost-white+
    +gold+
    +goldenrod+
    +gray+
    +green-yellow+
    +honeydew+
    +hot-pink+
    +indian-red+
    +ivory+
    +khaki+
    +lavender+
    +lavender-blush+
    +lawn-green+
    +lemon-chiffon+
    +light-blue+
    +light-coral+
    +light-cyan+
    +light-goldenrod+
    +light-goldenrod-yellow+
    +light-gray+
    +light-pink+
    +light-salmon+
    +light-sea-green+
    +light-sky-blue+
    +light-slate-blue+
    +light-slate-gray+
    +light-steel-blue+
    +light-yellow+
    +lime-green+
    +linen+
    +maroon+
    +medium-aquamarine+
    +medium-blue+
    +medium-orchid+
    +medium-purple+
    +medium-sea-green+
    +medium-slate-blue+
    +medium-spring-green+
    +medium-turquoise+
    +medium-violet-red+
    +midnight-blue+
    +mint-cream+
    +misty-rose+
    +moccasin+
    +navajo-white+
    +navy-blue+
    +old-lace+
    +olive-drab+
    +orange+
    +orange-red+
    +orchid+
    +pale-goldenrod+
    +pale-green+
    +pale-turquoise+
    +pale-violet-red+
    +papaya-whip+
    +peach-puff+
    +peru+
    +pink+
    +plum+
    +powder-blue+
    +purple+
    +rosy-brown+
    +royal-blue+
    +saddle-brown+
    +salmon+
    +sandy-brown+
    +sea-green+
    +seashell+
    +sienna+
    +sky-blue+
    +slate-blue+
    +slate-gray+
    +snow+
    +spring-green+
    +steel-blue+
    +tan+
    +thistle+
    +tomato+
    +turquoise+
    +violet+
    +violet-red+
    +wheat+
    +white+
    +white-smoke+
    +yellow-green+)

  ;; Need to export these since we don't hack SETF* yet
  (:export
    output-record-set-position*
    stream-set-cursor-position*
    stream-set-pointer-position*
    window-set-viewport-position*)

  ;; Some extensions until we decide what to do...
  (:export
    *accelerator-gestures*
    +iconic-view+
    accelerator-gesture
    accelerator-gesture-event
    accelerator-gesture-numeric-argument
    accept-values-command-parser
    catch-abort-gestures
    convert-from-absolute-to-relative-coordinates
    convert-from-ancestor-to-descendant-coordinates
    convert-from-descendant-to-ancestor-coordinates
    convert-from-relative-to-absolute-coordinates
    convert-to-stream-coordinates
    copy-textual-output-history
    #+Genera define-genera-application
    draw-standard-menu
    draw-triangle
    draw-triangle*
    drawing-surface-to-viewport-coordinates
    highlight-output-record-1
    iconic-view
    make-rectangle-set
    open-root-window
    open-window-stream
    position-window-near-carefully
    standard-rectangle-set
    stream-pointer-position-in-window-coordinates
    translate-positions
    viewport-to-drawing-surface-coordinates
    window-children
    window-clear-area
    window-expose
    window-inside-bottom
    window-inside-edges
    window-inside-height
    window-inside-left
    window-inside-right
    window-inside-size
    window-inside-top
    window-inside-width
    window-label
    window-label-size
    window-margins
    window-name
    window-parent
    window-root
    window-set-inside-edges
    window-set-inside-size
    window-stack-on-bottom
    window-stack-on-top
    window-stream-p
    window-visibility
    windowp
    window-top-level-window
    with-temporary-string)

  ;; CLIM 1.0 compatibility stubs
  #+CLIM-1-compatibility
  (:export
    *unsupplied-argument*
    +background-ink+
    +dialog-view+
    +foreground-ink+
    +menu-view+
    activation-character-p
    add-output-record-element
    add-text-style-mapping
    blip-character-p
    command-enabled-p
    compose-rotation-transformation
    compose-scaling-tansformation
    compose-translation-transformation
    delete-output-record-element
    dialog-view
    disable-command
    dragging-output-record
    draw-character
    draw-character*
    draw-string
    draw-string*
    enable-command
    frame-top-level-window
    make-color-ihs
    make-color-rgb
    map-over-output-record-elements
    map-over-output-record-elements-containing-point*
    map-over-output-record-elements-overlapping-region
    menu-view
    output-record-end-position*
    output-record-set-end-position*
    output-record-set-start-position*
    output-record-start-position
    output-record-start-position*
    output-recording-stream-current-output-record-stack
    output-recording-stream-output-history
    output-recording-stream-replay
    pointer-event-shift-mask
    set-frame-layout
    stream-draw-p
    stream-record-p
    stream-vsp
    with-activation-characters
    with-blip-characters
    with-frame-state-variables))

#+(and Genera lock-CLIM-packages) (setf (si:pkg-locked (find-package "CLIM")) t)


;; Now define all of the implementation packages
(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-UTILS
  (:use	CLIM-LISP CLIM-SYS CLIM)

  #+Genera
  (:import-from SYSTEM
    arglist)
  #+Genera
  (:import-from ZWEI
    indentation)

  #+Cloe-Runtime
  (:import-from CLOE
    arglist)
 
  #+Lucid
  (:import-from SYSTEM
    arglist)

  #+Allegro
  (:import-from EXCL
    arglist)

  #+(or Genera (not ANSI-90))
  (:shadow
    defun
    flet labels
    defgeneric defmethod)

  ;; Lucid and Allegro don't hack declarations properly for WITH-SLOTS
  ;; They do now except on some older versions
  #+(or Lucid (and Allegro (or :rs6000 (not (version>= 4 1)))))
  (:shadow
    with-slots)
  #+(or Lucid (and Allegro (or :rs6000 (not (version>= 4 1)))))
  (:export
    with-slots)

  ;; Fix CHAR-BITS and friends as best we can
  #+CCL-2
  (:shadow
    char=
    standard-char-p
    graphic-char-p
    alpha-char-p)
  #+CCL-2
  (:export
    char-bits
    char=
    standard-char-p
    graphic-char-p
    alpha-char-p)

  #+(and ANSI-90 Genera)
  (:import-from LISP
    string-char
    char-bits)
  #+Allegro
  (:shadowing-import-from CLTL1
    string-char
    char-bits)
  #+(or Allegro (and ANSI-90 Genera))
  (:export
    string-char
    char-bits)
  
  (:export
    arglist

    ;; From DEFUN
    *keyword-package*
    extract-declarations

    ;; From UTILITIES
    boolean
    with-collection
    collect
    with-gensyms
    with-fast-vector-references
    ignore-errors
    def-property-slot-macros
    def-property-slot-accessors
    define-unimplemented-protocol-method
    unimplemented warn-obsolete
    *multiprocessing-p*
    make-setf-function-name
    #+CLIM-1-compatibility define-compatibility-function
    safe-slot-value

    ;; From LISP-UTILITIES
    without-interrupts
    funcallable-p
    standard-io-environment-vars-and-vals 
    with-standard-io-environment 
    follow-synonym-stream
    fintern
    gensymbol 
    coordinate
    integerize-coordinate
    extended-char
    remove-word-from-string
    push-unique
    letf-globally
    letf-globally-if
    time-elapsed-p
    ;; ignore
    with-stack-list
    with-stack-list*
    evacuate-list
    with-stack-array
    with-keywords-removed
    remove-keywords
    with-stack-copy-of-list
    define-keywords
    dovector
    doseq
    dorest
    define-group
    with-warnings-for-definition
    defun-property
    defun-inline
    writing-clauses
    clause
    flatten-arglist
    make-pass-on-arglist
    ignore-arglist
    canonicalize-and-match-lambda-lists	 
    define-class-mixture
    do-delimited-substrings
    with-compile-time-local-property
    get-compile-time-local-property
    compile-time-property
    define-constructor
    define-constructor-using-prototype-instance
    once-only
    trap-on-error
    bind-to-list
    lambda-list-variables-used-in-body
    parameter-specifier-keyword
    find-class-that-works
    minf maxf minf-or maxf-or roundf
    simple-vector-push-extend
    simple-vector-insert-element

    ;; From CLOS
    find-dynamic-class

    ;; From QUEUE
    locking-queue
    make-queue
    queue 
    queue-contents-list
    map-over-queue
    queue-contents-type
    queue-empty-p
    queue-flush
    queue-full-p
    queue-get
    queue-last
    queue-length
    queue-next
    queue-pop
    queue-push
    queue-put
    queue-size
    queue-unget
    with-queue-locked

    ;; From PROTOCOLS
    protocol defprotocol find-protocol
    protocol-name protocol-roles protocol-operations
    role defrole find-role 
    role-slots
    operation defoperation
    operation-name operation-required-args operation-specs operation-extra-args
    *outer-self*
    generate-trampolines
    define-trampoline-template define-slot-trampoline-template
    define-protocol-class
    stream

    ;; From AUTOCONSTRUCTOR
    make-instance-with-constructor
    defautoconstructor
    autoconstructor
    disable-autoconstructors
    enable-autoconstructors

    ;; From CLIM-MACROS
    default-input-stream
    default-output-stream
    default-query-stream
    with-identity-transformation

    ;; From TRANSFORMATIONS
    standard-transformation
    identity-transformation
    translation-transformation

    ;; From REGIONS
    left top right bottom
    fix-rectangle
    opacity
    standard-opacity

    ;; Additional bounding rectangle stuff
    bounding-rectangle-set-edges
    bounding-rectangle-set-position*
    bounding-rectangle-shift-position
    bounding-rectangle-position-difference
    bounding-rectangle-position-equal
    bounding-rectangle-edges-equal
    bounding-rectangle-set-size
    bounding-rectangle-size-equal
    position-difference*

    ;; LTRBs
    ltrb-well-formed-p
    ltrb-equals-ltrb-p
    ltrb-size-equal
    ltrb-contains-point*-p
    ltrb-contains-ltrb-p
    ltrb-overlaps-ltrb-p
    ltrb-union
    ltrb-intersection
    ltrb-difference

    ;; Some random geometry
    pi-single-float
    2pi
    pi/2
    radians->degrees
    degrees->radians
    point-close-to-line-p
    point-inside-ellipse-p
    point-on-thick-ellipse-p
    elliptical-arc-box
    angle-between-angles-p
    2x2-singular-value-decomposition

    ;; From DESIGNS
    gray-color
    rgb-color
    ihs-color
    flipping-ink
    contrasting-ink
    color-luminosity
    composite-in
    composite-out
    composite-over
    contrasting-ink-index
    make-color-for-contrasting-ink
    make-gray-color-for-contrasting-ink
    decode-flipping-ink
    decode-pattern
    pattern-width
    pattern-height
    decode-rectangular-tile
    decode-tile-as-stipple
    flipping-ink
    make-design-from-output-record
    make-flipping-ink
    pattern
    rectangular-tile
    stencil
    stencil-array))

(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-SILICA
  (:nicknames SILICA)
  (:use	CLIM-LISP CLIM-SYS CLIM CLIM-UTILS)

  #+CCL-2
  (:shadowing-import-from CLIM-UTILS
    char=
    standard-char-p
    graphic-char-p
    alpha-char-p)

  #-CCL-2
  (:shadowing-import-from CLIM-UTILS
    defun
    flet labels
    defgeneric defmethod
    dynamic-extent
    #-Allegro non-dynamic-extent)

  #+(or Lucid (and Allegro (or :rs6000 (not (version>= 4 1)))))
  (:shadowing-import-from CLIM-UTILS
    with-slots)

  (:export
   *default-text-style*
   *null-text-style*
   *standard-character-set* 
   *undefined-text-style* 
   +highlighting-line-style+
   action-gadget
   activate-gadget-event
   allocate-space
   canvas
   char-character-set-and-index
   char-width
   click-event
   compose-space
   define-character-face
   define-character-face-added-mappings
   define-character-face-class
   define-display-device
   define-text-style-mappings 
   diacritic-char-p
   display-device 
   engraft-medium
   event-modifier-key-state
   event-sheet
   find-graft
   find-port
   find-port-type
   frame-manager
   frame-name
   frame-panes
   frame-shell
   gadget
   get-port-canonical-gesture-spec
   graft
   graftp
   handle-repaint
   intern-text-style
   make-frame-manager
   make-medium
   make-rectangle*
   medium
   merged-text-style 
   mirror-inside-edges*
   mirror-native-edges*
   mirror-region
   mirror-region*
   mirror-region-updated
   mirrored-sheet-mixin
   modifier-keysym
   mute-repainting-mixin
   parse-gesture-spec
   permanent-medium-sheet-output-mixin
   pointer-press-event
   pointer-release-event
   port
   port-color-cache
   port-draw-line*
   port-draw-rectangle*
   port-draw-text*
   port-event-wait
   port-force-output
   port-glyph-for-character
   port-pointer
   process-next-event
   process-event-locally
   push-button
   queue-event
   repaint-sheet
   set-sheet-mirror-edges*
   sheet-actual-native-edges
   sheet-direct-mirror
   sheet-height
   sheet-mute-input-mixin
   sheet-permanently-enabled-mixin
   sheet-width
   slider
   standard-sheet
   standard-sheet-input-mixin
   standarize-style
   stream-glyph-for-character
   string-height 
   string-width 
   text-field
   text-style-scale 
   toggle-button
   value-changed-gadget-event
   value-gadget
   window-configuration-event
   window-repaint-event
   with-sheet-medium
   stream-write-string-1
   port-note-cursor-change
   update-scrollbars
   event
   pointer-event-button
   medium-+y-upward-p
   scroller-pane
   medium-merged-text-style-valid
   port-beep
   port-server-path))

(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-INTERNALS
  (:use	CLIM-LISP CLIM-SYS CLIM CLIM-UTILS CLIM-SILICA)  

  #+CCL-2
  (:shadowing-import-from CLIM-UTILS
    char=
    standard-char-p
    graphic-char-p
    alpha-char-p)

  #-CCL-2
  (:shadowing-import-from CLIM-UTILS
    defun
    flet labels
    defgeneric defmethod
    dynamic-extent
    #-Allegro non-dynamic-extent)

  #+(or Lucid (and Allegro (or :rs6000 (not (version>= 4 1)))))
  (:shadowing-import-from CLIM-UTILS
    with-slots))


;; A package for casual use...
(#-ANSI-90 clim-lisp::defpackage #+ANSI-90 defpackage CLIM-USER
  (:use CLIM-LISP CLIM))
