;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Package: CLIM-INTERNALS; Base: 10; Lowercase: Yes -*-

;; $fiHeader: demo-prefill.lisp,v 1.2 92/02/24 13:09:22 cer Exp $

(in-package :clim-internals)

"Copyright (c) 1990, 1991 Symbolics, Inc.  All rights reserved."

;;; This file prefills generic function dispatch caches at load time so that
;;; there won't be so much delay starting things up the first time the application
;;; is run.  This file contains the things that aren't in CLIM:CLIM;PREFILL because
;;; they pertain to particular demos.


;;; (generate-prefill-dispatch-caches 'design)

(PREFILL-DISPATCH-CACHES
  (SIZE-FRAME-PANE
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::FLIGHT-PLANNER (EQL :COMMAND-MENU) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::FLIGHT-PLANNER (EQL :TITLE) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::FLIGHT-PLANNER (EQL :APPLICATION) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::FLIGHT-PLANNER (EQL :POINTER-DOCUMENTATION) T T T T) 

    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::CAD-DEMO (EQL :COMMAND-MENU) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::CAD-DEMO (EQL :TITLE) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::CAD-DEMO (EQL :APPLICATION) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::CAD-DEMO (EQL :POINTER-DOCUMENTATION) T T T T)
 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::LISP-LISTENER (EQL :COMMAND-MENU) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::LISP-LISTENER (EQL :TITLE) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::LISP-LISTENER (EQL :APPLICATION) T T T T) 
    (#+Cloe-Runtime CLOE-WINDOW-STREAM #+Genera SHEET-WINDOW-STREAM
     CLIM-DEMO::LISP-LISTENER (EQL :POINTER-DOCUMENTATION) T T T T)))

;;; (generate-prefill-dispatch-caches 'basic-view)

(PREFILL-DISPATCH-CACHES
  (ACCEPT-METHOD (CLIM-DEMO::ROUTE T T T T TEXTUAL-VIEW)
		 (CLIM-DEMO::AIRPORT T T T T TEXTUAL-VIEW)) 
  (PRESENT-METHOD (INTERSECTION T T T T T ICONIC-VIEW) 
		  (CLIM-DEMO::AIRPORT T T T T T ICONIC-VIEW) 
		  (CLIM-DEMO::AIRPORT T T T T T TEXTUAL-VIEW) 
		  (CLIM-DEMO::VOR T T T T T ICONIC-VIEW) 
		  (CLIM-DEMO::NDB T T T T T ICONIC-VIEW) 
		  (CLIM-DEMO::VISUAL-CHECKPOINT T T T T T ICONIC-VIEW)))

;;; (generate-prefill-dispatch-caches 'application-frame)

(PREFILL-DISPATCH-CACHES
  (CLIM-DEMO::ADD-NEW-OBJECT (CLIM-DEMO::CAD-DEMO CLIM-DEMO::LOGIC-ONE) 
			     (CLIM-DEMO::CAD-DEMO CLIM-DEMO::OUTPUT) 
			     (CLIM-DEMO::CAD-DEMO CLIM-DEMO::LOGIC-ZERO) 
			     (CLIM-DEMO::CAD-DEMO CLIM-DEMO::AND-GATE) 
			     (CLIM-DEMO::CAD-DEMO CLIM-DEMO::INPUT) 
			     (CLIM-DEMO::CAD-DEMO CLIM-DEMO::OR-GATE)) 
  (EXECUTE-FRAME-COMMAND (CLIM-DEMO::GRAPHICS-DEMO T) 
			 (CLIM-DEMO::FLIGHT-PLANNER T) 
			 (CLIM-DEMO::CAD-DEMO T)) 
  (FRAME-COMMAND-TABLE (CLIM-DEMO::GRAPHICS-DEMO) 
		       (CLIM-DEMO::FLIGHT-PLANNER) 
		       (CLIM-DEMO::CAD-DEMO) 
		       (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-CURRENT-LAYOUT (CLIM-DEMO::GRAPHICS-DEMO) 
			(CLIM-DEMO::FLIGHT-PLANNER) 
			(CLIM-DEMO::CAD-DEMO) 
			(CLIM-DEMO::LISP-LISTENER)) 
  ((SETF FRAME-CURRENT-LAYOUT) (T CLIM-DEMO::GRAPHICS-DEMO)) 
  (FRAME-DOCUMENT-HIGHLIGHTED-PRESENTATION (CLIM-DEMO::FLIGHT-PLANNER T T T T T T) 
					   (CLIM-DEMO::CAD-DEMO T T T T T T) 
					   (CLIM-DEMO::LISP-LISTENER T T T T T T)) 
  (FRAME-EXIT (CLIM-DEMO::GRAPHICS-DEMO) 
	      (CLIM-DEMO::FLIGHT-PLANNER)) 
  (FRAME-FIND-INNERMOST-APPLICABLE-PRESENTATION
    (CLIM-DEMO::GRAPHICS-DEMO T T T T) 
    (CLIM-DEMO::FLIGHT-PLANNER T T T T) 
    (CLIM-DEMO::CAD-DEMO T T T T) 
    (CLIM-DEMO::LISP-LISTENER T T T T)) 
  (FRAME-INPUT-CONTEXT-BUTTON-PRESS-HANDLER 
    (CLIM-DEMO::GRAPHICS-DEMO T T) 
    (CLIM-DEMO::FLIGHT-PLANNER T T) 
    (CLIM-DEMO::CAD-DEMO T T) 
    (CLIM-DEMO::LISP-LISTENER T T)) 
  (FRAME-NAME (CLIM-DEMO::GRAPHICS-DEMO) 
	      (CLIM-DEMO::FLIGHT-PLANNER) 
	      (CLIM-DEMO::CAD-DEMO) 
	      (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-PANES (CLIM-DEMO::GRAPHICS-DEMO) 
	       (CLIM-DEMO::FLIGHT-PLANNER) 
	       (CLIM-DEMO::CAD-DEMO) 
	       (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-POINTER-DOCUMENTATION-OUTPUT (CLIM-DEMO::GRAPHICS-DEMO) 
				      (CLIM-DEMO::FLIGHT-PLANNER) 
				      (CLIM-DEMO::CAD-DEMO) 
				      (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-QUERY-IO (CLIM-DEMO::GRAPHICS-DEMO) 
		  (CLIM-DEMO::FLIGHT-PLANNER) 
		  (CLIM-DEMO::CAD-DEMO) 
		  (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-REPLAY (CLIM-DEMO::GRAPHICS-DEMO T) 
		(CLIM-DEMO::FLIGHT-PLANNER T) 
		(CLIM-DEMO::CAD-DEMO T) 
		(CLIM-DEMO::LISP-LISTENER T)) 
  (FRAME-STANDARD-INPUT (CLIM-DEMO::GRAPHICS-DEMO) 
			(CLIM-DEMO::CAD-DEMO) 
			(CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-STANDARD-OUTPUT (CLIM-DEMO::GRAPHICS-DEMO) 
			 (CLIM-DEMO::FLIGHT-PLANNER) 
			 (CLIM-DEMO::CAD-DEMO) 
			 (CLIM-DEMO::LISP-LISTENER)) 
  (FRAME-TOP-LEVEL-SHEET (CLIM-DEMO::GRAPHICS-DEMO) 
			 (CLIM-DEMO::FLIGHT-PLANNER) 
			 (CLIM-DEMO::CAD-DEMO) 
			 (CLIM-DEMO::LISP-LISTENER)) 
  (INITIALIZE-INSTANCE (CLIM-DEMO::GRAPHICS-DEMO) 
		       (CLIM-DEMO::FLIGHT-PLANNER) 
		       (CLIM-DEMO::CAD-DEMO) 
		       (CLIM-DEMO::LISP-LISTENER)) 
  (LAYOUT-FRAME-PANES (CLIM-DEMO::GRAPHICS-DEMO T) 
		      (CLIM-DEMO::FLIGHT-PLANNER T) 
		      (CLIM-DEMO::CAD-DEMO T) 
		      (CLIM-DEMO::LISP-LISTENER T)) 
  (MAP-OVER-OUTPUT-RECORDS-OVERLAPPING-REGION
    (T CLIM-DEMO::CAD-DEMO T)) 
  (MAP-OVER-OUTPUT-RECORDS-CONTAINING-POSITION
    (T CLIM-DEMO::CAD-DEMO T T)) 
  (READ-FRAME-COMMAND (CLIM-DEMO::GRAPHICS-DEMO) 
		      (CLIM-DEMO::FLIGHT-PLANNER) 
		      (CLIM-DEMO::CAD-DEMO)) 
  (REDISPLAY-FRAME-PANES (CLIM-DEMO::GRAPHICS-DEMO) 
			 (CLIM-DEMO::FLIGHT-PLANNER) 
			 (CLIM-DEMO::CAD-DEMO)) 
  (REPLAY-OUTPUT-RECORD (CLIM-DEMO::CAD-DEMO T)) 
  (RUN-FRAME-TOP-LEVEL (CLIM-DEMO::GRAPHICS-DEMO) 
		       (CLIM-DEMO::FLIGHT-PLANNER) 
		       (CLIM-DEMO::CAD-DEMO) 
		       (CLIM-DEMO::LISP-LISTENER)) 
  ((SETF FRAME-CURRENT-LAYOUT) (T CLIM-DEMO::GRAPHICS-DEMO)) 
  (SHARED-INITIALIZE (CLIM-DEMO::GRAPHICS-DEMO T) 
		     (CLIM-DEMO::FLIGHT-PLANNER T) 
		     (CLIM-DEMO::CAD-DEMO T) 
		     (CLIM-DEMO::LISP-LISTENER T)))
